import test from 'node:test';
import assert from 'node:assert/strict';
import {newState,validateSave,pullOne,summon,upgrade} from '../state.js';
import {HEROES,levelCost,maxHP} from '../data.js';

test('A fresh journey is playable without gacha and has a free ten-pull',()=>{const s=newState();assert.equal(s.party.length,2);assert.equal(s.crystals,1600);assert.ok(s.roster.in&&s.roster.nam);});
test('A rejected purchase is atomic and costs no resources',()=>{const s=newState();s.crystals=159;const before=JSON.stringify(s);assert.deepEqual(summon(s,1),{ok:false,results:[]});assert.equal(JSON.stringify(s),before);assert.equal(summon(s,9).ok,false);});
test('Ten pulls charge once and guarantee a four-star or better',()=>{const s=newState();const r=summon(s,10,()=>.9);assert.equal(r.results.length,10);assert.equal(s.crystals,0);assert.equal(s.totalPulls,10);assert.equal(r.results[9].rarity,4);assert.equal(s.pity4,0);});
test('The fiftieth pull guarantees a five-star and resets both counters',()=>{const s=newState();let out;for(let i=0;i<50;i++)out=pullOne(s,()=>.9);assert.equal(out.rarity,5);assert.equal(s.pity5,0);assert.equal(s.pity4,0);});
test('Base probability thresholds distinguish 2%, 12%, and 86%',()=>{for(const [v,r] of [[.01999,5],[.02,4],[.13999,4],[.14,3],[.9999,3]]){const s=newState();assert.equal(pullOne(s,()=>v).rarity,r);}});
test('Ten-pull and single-pull logic produce the same state',()=>{const a=newState(),b=newState();a.crystals=b.crystals=1600;let i=0,j=0;const seq=[.9,.7,.1,.02,.8,.013,.6,.34,.96,.49];summon(a,10,()=>seq[(i++)%seq.length]);for(let k=0;k<10;k++)summon(b,1,()=>seq[(j++)%seq.length]);assert.equal(a.ore,b.ore);assert.equal(a.crystals,b.crystals);assert.equal(a.pity5,b.pity5);assert.equal(a.pity4,b.pity4);assert.deepEqual(a.roster,b.roster);});
test('Duplicates cap at rank six and still grant ore',()=>{const s=newState();for(let i=0;i<15;i++)pullOne(s,()=>.05);const h=HEROES.filter(h=>h.rarity===4)[0];assert.equal(s.roster[h.id].rank,6);assert.equal(s.ore,18+15*12);});
test('Level upgrades deduct the shown cost and restore the correct health',()=>{const s=newState(),cost=levelCost(1);assert.equal(upgrade(s,'in'),true);assert.equal(s.ore,18-cost);assert.equal(s.roster.in.level,2);assert.equal(s.roster.in.hp,maxHP(HEROES[0],2));assert.equal(upgrade(s,'mek'),false);s.roster.in.level=20;assert.equal(upgrade(s,'in'),false);});
test('Save validation rejects incompatible data and sanitizes imported state',()=>{assert.throws(()=>validateSave({version:9}));const s=newState();s.crystals=Infinity;s.position={x:999,z:-999};s.party=['mek','in','in','unknown'];s.pity5=500;s.pity4=400;s.roster.in.level=-20;s.settings.sensitivity=NaN;const n=validateSave(s);assert.equal(n.crystals,1600);assert.deepEqual(n.party,['in']);assert.equal(n.pity5,49);assert.equal(n.pity4,9);assert.equal(n.position.x,248);assert.equal(n.position.z,-248);assert.equal(n.roster.in.level,1);assert.equal(n.settings.sensitivity,1);});
test('Boss completion survives the save round trip',()=>{const s=newState();s.bossDefeated=true;s.beacons.push('forest','wetland','wind','mountain');s.story=4;s.chests=['chest-0','chest-0','bad'];const n=validateSave(JSON.parse(JSON.stringify(s)));assert.equal(n.story,4);assert.equal(n.bossDefeated,true);assert.equal(n.beacons.length,5);assert.deepEqual(n.chests,['chest-0']);});
test('An imported inherited-property name cannot enter the party',()=>{const s=newState();s.party=['constructor','toString','__proto__'];assert.deepEqual(validateSave(s).party,['in','nam']);});
test('Defeated members remain defeated, and the active slot changes to a living member',()=>{const s=newState();s.roster.in.hp=0;s.active=0;s.story=1.75;const n=validateSave(s);assert.equal(n.roster.in.hp,0);assert.equal(n.active,1);assert.equal(n.story,1);});
