import * as THREE from 'three';
import { World } from './world.js';
import { UI } from './ui.js';
import { loadState, persist } from './state.js';
import { HEROES, REGIONS, PUZZLES, REACTIONS, getHero, maxHP, attackPower } from './data.js';
import { height, clamp, regionAt } from './terrain.js';

export class Game {
  constructor(){
    const loaded=loadState();this.state=loaded.state;this.loadError=loaded.error;this.started=false;this.keys={};this.move={x:0,y:0};this.cameraYaw=0;this.cameraPitch=.37;this.cameraDistance=13;
    this.player={x:this.state.position.x,z:this.state.position.z,y:height(this.state.position.x,this.state.position.z),vy:0,grounded:true};this.stamina=100;this.shield=0;this.shieldTime=0;this.invul=0;this.normalCD=0;this.skillCD={};this.dodgeTime=0;this.dodgeCD=0;this.gliding=false;this.swimming=false;this.climbing=false;this.nearest=null;this.lastRegion='campus';this.effects=[];this.projectiles=[];this.time=0;this.uiTime=0;this.saveTime=0;this.attackAnim=0;this.lastDX=0;this.lastDZ=-1;this.waypoint=null;
    const canvas=document.querySelector('#view');this.renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.12;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;
    this.scene=new THREE.Scene();this.scene.background=new THREE.Color('#b8d0d7');this.scene.fog=new THREE.Fog('#c8d6d2',120,450);this.camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.15,2000);this.camera.position.set(69,39,82);this.camera.lookAt(0,5,-17);
    this.scene.add(new THREE.HemisphereLight('#fff3db','#526746',2.2));this.sun=new THREE.DirectionalLight('#ffedcc',2.6);this.sun.position.set(-50,90,30);this.sun.castShadow=true;this.sun.shadow.mapSize.set(1024,1024);this.sun.shadow.camera.left=-45;this.sun.shadow.camera.right=45;this.sun.shadow.camera.top=45;this.sun.shadow.camera.bottom=-45;this.sun.shadow.camera.near=1;this.sun.shadow.camera.far=200;this.sun.shadow.bias=-.0006;this.sun.shadow.normalBias=.03;this.scene.add(this.sun,this.sun.target);
    this.world=new World(this.scene);this.ui=new UI(this);this.heroes={};this.applyQuality();this.setupInput();
  }
  async init(){
    await document.fonts.load('600 60px "Noto Sans Thai"');
    await this.world.load((v,n)=>this.ui.progress(v,n));for(const h of HEROES){const actor=this.world.createActor(h.model,2.5,h.color);actor.root.visible=false;this.scene.add(actor.root);this.heroes[h.id]=actor;}
    this.glider=this.buildGlider();this.world.restore(this.state);this.syncHero();if(this.world.blocked(this.player.x,this.player.z))this.place(0,27);this.ready=true;this.ui.ready(this.state.playtime>0||this.state.totalPulls>0);if(this.loadError)this.ui.toast(this.loadError,6500);
    this.clock=new THREE.Clock();this.frame();
    if(new URLSearchParams(location.search).has('qa'))window.__game=this;
  }
  buildGlider(){const g=new THREE.Group(),material=new THREE.MeshStandardMaterial({color:'#e9c0cb',side:THREE.DoubleSide,roughness:.8,transparent:true,opacity:.9});
    for(const side of [-1,1]){const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute([0,0,0,side*3.2,.15,-.6,side*1.8,0,1.2,0,0,0,side*1.8,0,1.2,0,0,.8],3));geo.computeVertexNormals();g.add(new THREE.Mesh(geo,material));const beam=new THREE.Mesh(new THREE.CylinderGeometry(.035,.035,3.3,6),new THREE.MeshStandardMaterial({color:'#b19c7a'}));beam.rotation.z=side*Math.PI/2;beam.position.set(side*1.6,.03,-.3);g.add(beam);}g.visible=false;this.scene.add(g);return g;}
  get hero(){return getHero(this.state.party[this.state.active]);}
  get record(){return this.state.roster[this.hero.id];}
  get paused(){return !this.started||this.ui.panel.open||document.hidden;}
  start(){this.started=true;document.querySelector('#start').hidden=true;document.querySelector('#hud').hidden=false;document.querySelector('#view').focus({preventScroll:true});this.camera.position.set(this.player.x+3,this.player.y+7,this.player.z+12);this.clearInput();this.ui.banner(regionAt(this.player.x,this.player.z));this.ui.toast('เริ่มจากคุยกับพี่พิมที่ลานเกียร์ · กด F เมื่อเข้าใกล้');this.sound('wish');}
  applyQuality(){const q=this.state.settings.quality,mobile=matchMedia('(pointer: coarse)').matches,low=q==='low'||(q==='auto'&&(mobile||navigator.deviceMemory<=4));this.renderer.setPixelRatio(low?Math.min(devicePixelRatio,1):Math.min(devicePixelRatio,1.75));this.renderer.shadowMap.enabled=!low;this.resize();}
  resize(){this.renderer.setSize(innerWidth,innerHeight,false);this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();}
  clearInput(){this.keys={};this.move.x=this.move.y=0;const knob=document.querySelector('#joystick-knob');if(knob)knob.style.transform='';}
  setupInput(){
    if(matchMedia('(pointer: coarse)').matches)document.body.classList.add('touch');window.addEventListener('resize',()=>this.resize());window.addEventListener('blur',()=>{this.clearInput();if(this.started)this.save();});document.addEventListener('visibilitychange',()=>{this.clearInput();if(document.hidden)this.save();});window.addEventListener('pagehide',()=>this.save());
    window.addEventListener('keydown',e=>{const key=e.key.toLowerCase();if(this.ui.panel.open){if(key==='escape'){e.preventDefault();this.ui.close();}return;}if(!this.started)return;
      if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(key))e.preventDefault();this.keys[key]=true;if(e.repeat)return;
      if(key===' '){this.jump();}else if(key==='j')this.attack('normal');else if(key==='e')this.attack('skill');else if(key==='q')this.attack('burst');else if(key==='f')this.interact();else if(key==='x')this.dodge();else if(/^[1-4]$/.test(key))this.switchHero(Number(key)-1);
      else if(['m','g','t','h','escape'].includes(key)){e.preventDefault();this.ui.open(({m:'map',g:'wish',t:'team',h:'help',escape:'settings'})[key]);}
    });window.addEventListener('keyup',e=>this.keys[e.key.toLowerCase()]=false);
    const canvas=document.querySelector('#view');let look=null,moved=0;
    canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('pointerdown',e=>{if(this.paused)return;look={id:e.pointerId,x:e.clientX,y:e.clientY};moved=0;canvas.setPointerCapture(e.pointerId);});
    canvas.addEventListener('pointermove',e=>{if(!look||look.id!==e.pointerId||this.paused)return;const dx=e.clientX-look.x,dy=e.clientY-look.y;moved+=Math.abs(dx)+Math.abs(dy);this.cameraYaw-=dx*.005*this.state.settings.sensitivity;this.cameraPitch=clamp(this.cameraPitch+dy*.004*this.state.settings.sensitivity*(this.state.settings.invert?-1:1),.08,1.1);look.x=e.clientX;look.y=e.clientY;});
    canvas.addEventListener('pointerup',e=>{if(look?.id===e.pointerId){if(moved<7&&e.pointerType==='mouse'&&e.button===0)this.attack('normal');look=null;}});canvas.addEventListener('pointercancel',()=>look=null);canvas.addEventListener('wheel',e=>{if(this.paused)return;e.preventDefault();this.cameraDistance=clamp(this.cameraDistance+e.deltaY*.01,7,23);},{passive:false});
    const joy=document.querySelector('#joystick');let joyId=null;
    const updateJoy=e=>{const b=joy.getBoundingClientRect(),dx=e.clientX-b.left-b.width/2,dy=e.clientY-b.top-b.height/2,limit=b.width*.32,len=Math.hypot(dx,dy),factor=Math.min(1,limit/(len||1));this.move.x=dx*factor/limit;this.move.y=-dy*factor/limit;document.querySelector('#joystick-knob').style.transform=`translate(${dx*factor}px,${dy*factor}px)`;};
    joy.addEventListener('pointerdown',e=>{if(this.paused)return;joyId=e.pointerId;joy.setPointerCapture(e.pointerId);updateJoy(e);});joy.addEventListener('pointermove',e=>{if(e.pointerId===joyId)updateJoy(e);});const endJoy=e=>{if(e.pointerId===joyId){joyId=null;this.move.x=this.move.y=0;document.querySelector('#joystick-knob').style.transform='';}};joy.addEventListener('pointerup',endJoy);joy.addEventListener('pointercancel',endJoy);
    for(const [id,key] of [['sprint-button','shift'],['climb-button','c']]){const b=document.querySelector('#'+id);b.addEventListener('pointerdown',e=>{if(this.paused)return;b.setPointerCapture(e.pointerId);this.keys[key]=true;});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>this.keys[key]=false);}
  }
  syncHero(){for(const a of Object.values(this.heroes))a.root.visible=false;const a=this.heroes[this.hero.id];if(!a)return;a.root.visible=true;a.root.position.set(this.player.x,this.player.y,this.player.z);a.root.rotation.y=Math.atan2(this.lastDX,this.lastDZ);a.play('Idle');this.actor=a;}
  switchHero(i){if(i<0||i>=this.state.party.length||i===this.state.active)return;if(this.state.roster[this.state.party[i]].hp<=0){this.ui.toast('สมาชิกนี้หมดสภาพ พักที่สถานีเพื่อฟื้นฟู');return;}this.state.active=i;this.syncHero();this.attackAnim=0;this.spark(new THREE.Vector3(this.player.x,this.player.y+1.5,this.player.z),this.hero.color,10);this.sound('switch');}
  jump(){if(this.paused)return;const p=this.player,ground=this.world.groundAt(p.x,p.z);if(p.grounded||this.swimming){p.vy=8.8;p.grounded=false;this.swimming=false;this.gliding=false;this.actor.play('Jump_Start',true);this.sound('jump');}else if(p.y-ground>.7){this.gliding=!this.gliding;if(this.gliding){p.vy=Math.min(p.vy,0);this.ui.toast('เครื่องร่อนเปิด · ใช้ความอึดต่อเนื่อง',1600);}}}
  dodge(){if(this.paused||this.dodgeCD>0||this.stamina<20)return;this.dodgeTime=.35;this.dodgeCD=1.2;this.stamina-=20;this.invul=.55;this.actor.play('Dodge_Forward',true);this.attackAnim=.35;this.sound('dodge');}
  target(radius){let target=null,d=radius;for(const e of this.world.enemies){if(e.dead||(e.boss&&this.state.story<2))continue;const dist=Math.hypot(e.x-this.player.x,e.z-this.player.z);if(dist<d&&Math.abs(e.root.position.y-this.player.y)<12){target=e;d=dist;}}return target;}
  attack(kind){if(this.paused||this.record.hp<=0)return;const h=this.hero,r=this.record;
    if(kind==='normal'&&this.normalCD>0)return;if(kind==='skill'&&(this.skillCD[h.id]||0)>0){this.ui.toast('สกิลยังอยู่ในช่วงพัก',1200);return;}if(kind==='burst'&&r.energy<60)return;
    const power=attackPower(h,r.level,r.rank),position=new THREE.Vector3(this.player.x,this.player.y+1.25,this.player.z);this.attackAnim=kind==='normal'?.4:.8;this.actor.play(h.element==='mech'?'2H_Melee_Attack_Slice':h.element==='geo'?'1H_Melee_Attack_Chop':'Spellcast_Shoot',true);this.sound(kind);
    if(kind==='normal'){this.normalCD=h.element==='code'?.3:.42;r.energy=clamp(r.energy+2,0,100);const target=this.target(23),mesh=new THREE.Mesh(new THREE.SphereGeometry(.2,8,6),new THREE.MeshBasicMaterial({color:h.color}));mesh.position.copy(position);this.scene.add(mesh);this.projectiles.push({mesh,target,direction:new THREE.Vector3(this.lastDX,0,this.lastDZ),life:1.4,power:power*.8,element:h.element,color:h.color});}
    else{if(kind==='skill'){this.skillCD[h.id]=6;r.energy=clamp(r.energy+16,0,100);if(h.element==='geo'){this.shield=70;this.shieldTime=8;}if(h.element==='code')this.normalCD=0;}
      else{r.energy-=60;if(h.element==='atom')for(const id of this.state.party){const rs=this.state.roster[id];rs.hp=Math.min(maxHP(getHero(id),rs.level),rs.hp+70);}if(h.element==='geo'){this.shield=120;this.shieldTime=10;}}
      const radius=kind==='burst'?27:16,damage=power*(kind==='burst'?3.5:1.6);this.ring(position,radius,h.color,.7);this.spark(position,h.color,24);
      for(const e of this.world.enemies){if(e.dead||(e.boss&&this.state.story<2))continue;if(Math.hypot(e.x-this.player.x,e.z-this.player.z)<=radius&&Math.abs(e.root.position.y-this.player.y)<12)this.hit(e,damage,h.element,h.color);}
    }
  }
  hit(enemy,power,element,color){if(enemy.dead)return;let reaction=null;if(enemy.element&&enemy.element!==element&&enemy.elementTime>0){const key=[enemy.element,element].sort().join('+');reaction=REACTIONS[key]||REACTIONS.default;power*=reaction.mult;enemy.element=null;enemy.elementTime=0;}else{enemy.element=element;enemy.elementTime=6;}
    enemy.hp-=power;const p=new THREE.Vector3(enemy.x,enemy.root.position.y+(enemy.boss?5:2),enemy.z);this.ui.damage(Math.round(power),p,color);if(reaction)this.ui.damage(reaction.name,p.clone().add(new THREE.Vector3(0,1,0)),null,true);this.spark(p,color,6);this.record.energy=clamp(this.record.energy+3,0,100);if(enemy.hp<=0)this.kill(enemy);else if(!enemy.windup)enemy.play('Punch',true);
  }
  kill(enemy){enemy.dead=true;enemy.root.visible=false;if(enemy.telegraph){this.disposeEffect(enemy.telegraph);enemy.telegraph=null;}enemy.windup=0;
    if(enemy.boss){const first=!this.state.bossDefeated;this.state.bossDefeated=true;if(this.state.story<3)this.state.story=3;this.state.crystals+=first?800:160;this.state.ore+=first?40:12;this.state.beacons=[...new Set([...this.state.beacons,'mountain'])];this.world.restore(this.state);this.ui.toast(first?'หยุด ATLAS สำเร็จ · +800 ✧ · กลับไปหาพี่พิม':'ท้าทายสำเร็จ · +160 ✧ · แร่ +12',6500);this.waypoint=first?{...REGIONS[0]}:null;this.sound('wish');}
    else{if(!this.state.kills.includes(enemy.id)){this.state.kills.push(enemy.id);this.state.crystals+=30;this.state.ore+=3;}this.sound('hit');}
    this.save();
  }
  hurt(amount){if(this.invul>0)return;if(this.shield>0){const absorbed=Math.min(amount,this.shield);this.shield-=absorbed;amount-=absorbed;}if(amount<=0)return;this.record.hp=Math.max(0,this.record.hp-amount);this.invul=.75;this.sound('hurt');this.ui.damage('-'+Math.round(amount),new THREE.Vector3(this.player.x,this.player.y+2.4,this.player.z),'#ffb0a6');
    if(this.record.hp<=0){const next=this.state.party.findIndex(id=>this.state.roster[id].hp>0);if(next>=0){this.state.active=next;this.syncHero();this.ui.toast('สมาชิกหมดสภาพ · สลับไป '+this.hero.name);}else{this.place(0,27);this.heal();this.resetBoss();this.ui.toast('ทีมกลับมาที่ลานเกียร์ · พักและปรับทีมก่อนลองอีกครั้ง',5000);this.save();}}
  }
  heal(){for(const id of this.state.party){const r=this.state.roster[id];r.hp=maxHP(getHero(id),r.level);r.energy=Math.max(r.energy,35);}this.stamina=100;this.shield=0;this.invul=1;}
  place(x,z){this.player.x=x;this.player.z=z;this.player.y=this.world.groundAt(x,z);this.player.vy=0;this.player.grounded=true;this.gliding=false;this.swimming=false;this.climbing=false;if(this.actor)this.actor.root.position.set(x,this.player.y,z);this.camera.position.set(x+2,this.player.y+6,z+12);this.clearInput();}
  teleport(id){const r=REGIONS.find(r=>r.id===id);if(!r||!this.state.beacons.includes(id))return;this.place(r.x+4,r.z+4);this.heal();this.resetBoss();this.save();this.ui.toast('เดินทางถึง '+r.name);}
  resetBoss(){const b=this.world.boss;if(!b)return;if(b.telegraph){this.disposeEffect(b.telegraph);b.telegraph=null;}b.windup=0;b.hp=b.maxHP;b.cooldown=3;b.x=b.homeX;b.z=b.homeZ;b.root.position.set(b.x,this.world.groundAt(b.x,b.z),b.z);b.element=null;b.elementTime=0;b.play('Idle');}
  repeatBoss(){this.resetBoss();this.world.boss.dead=false;this.world.boss.root.visible=true;this.ui.toast('เริ่มท้าทาย ATLAS อีกครั้ง');}
  activateBeacon(id){if(this.state.beacons.includes(id))return;this.state.beacons.push(id);if(PUZZLES[id]){this.state.crystals+=160;this.state.ore+=10;}this.heal();if(this.state.story===1&&['forest','wetland','wind'].every(r=>this.state.beacons.includes(r))){this.state.story=2;this.waypoint={...REGIONS[4]};this.ui.toast('โครงข่ายครบแล้ว · มุ่งหน้าสู่สันเขาศิลา',4500);}else if(PUZZLES[id]){const next=REGIONS.find(r=>PUZZLES[r.id]&&!this.state.beacons.includes(r.id));this.waypoint=next?{...next}:null;}this.world.restore(this.state);this.save();this.sound('wish');}
  interact(){if(this.paused||!this.nearest)return;const n=this.nearest,s=this.state;
    if(n.type==='chest'){if(s.chests.includes(n.id))return;s.chests.push(n.id);s.crystals+=80;s.ore+=6;n.root.visible=false;this.nearest=null;this.save();this.sound('chest');this.ui.toast('หีบสำรวจ · +80 ✧ · แร่ +6');}
    else if(n.type==='npc'){if(s.story===0)this.ui.dialogue('พี่พิม · เสียงเรียกจากลานเกียร์','โครงข่ายที่เชื่อมทุกภูมิประเทศดับลง อินกับนามต้องร่วมกันเปิดสถานีป่าจามจุรี อุทยานร้อยปี และเนินกังหัน เมื่อสถานีทั้งสามพร้อม เราจะค้นพบว่าอะไรเกิดขึ้นบนสันเขาศิลา',[{label:'รับภารกิจ · 320 ✧',action:'acceptquest',primary:true},{label:'กลับมาใหม่',action:'close'}]);
      else if(s.story===3)this.ui.dialogue('พี่พิม · แสงที่กลับคืนมา','คุณหยุด ATLAS และฟื้นฟูโครงข่ายสำเร็จแล้ว พลังของแต่ละคนมีข้อจำกัด แต่ทีมที่เข้าใจกันไปได้ไกลกว่าเดิมเสมอ',[{label:'จบภารกิจ · รับ 640 ✧',action:'finishquest',primary:true}]);
      else this.ui.dialogue('พี่พิม · ผู้ประสานงาน',s.story===4?'โครงข่ายกลับมาสมดุลแล้ว ออกไปสำรวจให้ครบ หรือกลับไปท้าทาย ATLAS อีกครั้งได้เลย':'ลองเปิดแผนที่แล้วตั้งเป้าหมายไปสถานีที่ยังไม่เปิด เคมีกับไฟฟ้าประสานพลังกันได้ อย่าลืมเพิ่มระดับด้วยแร่ที่หาได้',[{label:'พักฟื้นทีม',action:'heal',primary:true},{label:'เดินทางต่อ',action:'close'}]);
    }else if(n.type==='beacon'){if(n.id==='mountain'&&s.story<2){this.ui.dialogue('โครงข่ายยังไม่พร้อม','เปิดสถานีป่า อุทยาน และเนินกังหันให้ครบทั้งสามแห่งก่อน เครื่องควบคุมสันเขาจึงจะตอบสนอง',[{label:'เดินทางต่อ',action:'close',primary:true}]);return;}
      if(!s.beacons.includes(n.id)){if(PUZZLES[n.id]){if(s.story===0){this.ui.dialogue('สถานีควบคุม','ไปคุยกับพี่พิมที่ลานเกียร์เพื่อรับเครื่องมือปรับเทียบก่อน',[{label:'กลับไปสำรวจ',action:'close',primary:true}]);return;}this.ui.puzzle(n.id);}else{this.activateBeacon(n.id);this.ui.toast('เปิดสถานีสันเขาศิลาแล้ว · วาร์ปได้');}}
      else{if(n.id==='mountain'&&!this.world.boss.dead&&this.world.boss.hp<this.world.boss.maxHP){this.ui.toast('สถานีพักใช้ไม่ได้ระหว่างต่อสู้กับ ATLAS');return;}this.ui.dialogue(n.name,'สถานีที่เปิดแล้วเป็นจุดพักและจุดวาร์ป ใช้แผนที่เพื่อเดินทางไปสถานีอื่น',[{label:'ฟื้นฟูทีม',action:'heal',primary:true},...(n.id==='mountain'&&s.bossDefeated&&this.world.boss.dead?[{label:'ท้าทาย ATLAS อีกครั้ง',action:'repeatboss'}]:[]),{label:'เดินทางต่อ',action:'close'}]);}
    }
  }
  movement(dt){const p=this.player,oldGround=this.world.groundAt(p.x,p.z);let ix=(this.keys.d||this.keys.arrowright?1:0)-(this.keys.a||this.keys.arrowleft?1:0)+this.move.x,iy=(this.keys.w||this.keys.arrowup?1:0)-(this.keys.s||this.keys.arrowdown?1:0)+this.move.y;const len=Math.hypot(ix,iy);if(len>1){ix/=len;iy/=len;}
    let dx=ix*Math.cos(this.cameraYaw)-iy*Math.sin(this.cameraYaw),dz=-ix*Math.sin(this.cameraYaw)-iy*Math.cos(this.cameraYaw),moving=Math.hypot(dx,dz)>.08,sprint=this.keys.shift&&moving&&this.stamina>0&&!this.swimming;
    let speed=this.swimming?4.5:this.gliding?10:sprint?13:7.5;this.climbing=false;
    if(this.dodgeTime>0){dx=this.lastDX;dz=this.lastDZ;speed=25;moving=true;}
    let nx=clamp(p.x+dx*speed*dt,-248,248),nz=clamp(p.z+dz*speed*dt,-248,248),ground=this.world.groundAt(nx,nz),slope=(this.world.groundAt(nx+dx*.8,nz+dz*.8)-ground)/.8;
    if(slope>.52&&p.y<ground+.5&&moving){if(this.keys.c&&this.stamina>0){this.climbing=true;nx=p.x+dx*3.5*dt;nz=p.z+dz*3.5*dt;ground=this.world.groundAt(nx,nz);}else{nx=p.x;nz=p.z;ground=oldGround;if(this.time-(this.climbHintTime||0)>5){this.ui.toast('เนินชัน · กด C หรือปุ่มปีนค้างพร้อมเดิน',2000);this.climbHintTime=this.time;}}}
    if(!this.world.blocked(nx,nz)){p.x=nx;p.z=nz;}else if(!this.world.blocked(nx,p.z))p.x=nx;else if(!this.world.blocked(p.x,nz))p.z=nz;ground=this.world.groundAt(p.x,p.z);
    if(moving){this.lastDX=dx/(Math.hypot(dx,dz)||1);this.lastDZ=dz/(Math.hypot(dx,dz)||1);this.actor.root.rotation.y=Math.atan2(dx,dz);}
    const inWater=regionAt(p.x,p.z).id==='wetland'&&ground<.1&&p.y<.55&&p.vy<=0;
    if(inWater){this.swimming=true;this.gliding=false;p.y=Math.max(ground,.45-1.15);p.vy=0;p.grounded=false;}
    else{this.swimming=false;if(!p.grounded){p.vy-=dt*(this.gliding?2.5:22);if(this.gliding)p.vy=Math.max(p.vy,-2.5);p.y+=p.vy*dt;}
      else{if(p.y-ground>1.2){p.grounded=false;p.vy=0;}else p.y=ground;}
      if(p.y<=ground){p.y=ground;p.grounded=true;p.vy=0;this.gliding=false;}
    }
    if(this.gliding||this.swimming||this.climbing||(sprint&&moving))this.stamina=clamp(this.stamina-dt*(this.climbing?15:this.swimming?6:this.gliding?7:11),0,100);else this.stamina=clamp(this.stamina+dt*17,0,100);
    if(this.stamina<=0){this.gliding=false;if(this.swimming){this.place(0,27);this.record.hp=Math.max(1,this.record.hp-40);this.stamina=35;this.ui.toast('ความอึดหมดในน้ำ · กลับไปพักที่ลานเกียร์',4000);}}
    this.actor.root.position.set(p.x,p.y,p.z);this.actor.mixer.update(dt);if(this.attackAnim<=0)this.actor.play(this.gliding||!p.grounded?'Jump_Idle':moving?'Running_A':'Idle');this.glider.visible=this.gliding;this.glider.position.set(p.x,p.y+2.6,p.z);this.glider.rotation.y=this.actor.root.rotation.y;
    this.nearest=null;let nearD=4.8;for(const n of [...this.world.beacons,...this.world.chests,this.world.npc]){if(n.type==='chest'&&this.state.chests.includes(n.id))continue;const d=Math.hypot(n.x-p.x,n.z-p.z);if(d<nearD&&Math.abs(height(n.x,n.z)-p.y)<5){this.nearest=n;nearD=d;}}
    const region=regionAt(p.x,p.z);if(region.id!==this.lastRegion){this.lastRegion=region.id;this.ui.banner(region);}
  }
  updateEnemies(dt){for(const e of this.world.enemies){if(e.dead)continue;const d=Math.hypot(e.x-this.player.x,e.z-this.player.z);if(d>110)continue;e.mixer.update(dt);e.elementTime=Math.max(0,e.elementTime-dt);if(e.boss&&this.state.story<2)continue;e.cooldown-=dt;
      if(e.windup>0){e.windup-=dt;if(e.telegraph)e.telegraph.material.opacity=.2+.5*(1-e.windup/e.windupDuration);if(e.windup<=0){const dist=Math.hypot(this.player.x-e.attackX,this.player.z-e.attackZ);if(dist<e.attackRadius&&Math.abs(this.player.y-height(e.attackX,e.attackZ))<6)this.hurt(e.boss?(e.hp<e.maxHP/2?52:38):17);this.ring(new THREE.Vector3(e.attackX,height(e.attackX,e.attackZ)+.2,e.attackZ),e.attackRadius,'#e7a799',.4);this.disposeEffect(e.telegraph);e.telegraph=null;e.cooldown=e.boss?(e.hp<e.maxHP/2?1.1:2):1.5;e.play('Idle');}continue;}
      if(d>(e.boss?50:24)){if(e.boss&&d>65&&e.hp<e.maxHP)this.resetBoss();e.play('Idle');continue;}
      if(d>(e.boss?9:2.5)){const nx=e.x+(this.player.x-e.x)/d*dt*(e.boss?4:3),nz=e.z+(this.player.z-e.z)/d*dt*(e.boss?4:3);if(Math.hypot(nx-e.homeX,nz-e.homeZ)<(e.boss?20:18)){e.x=nx;e.z=nz;e.root.position.set(nx,Math.max(this.world.groundAt(nx,nz),.35),nz);e.root.rotation.y=Math.atan2(this.player.x-nx,this.player.z-nz);e.play('Walking');}}
      else if(e.cooldown<=0){e.attackX=this.player.x;e.attackZ=this.player.z;e.attackRadius=e.boss?(e.hp<e.maxHP/2?8:6):2;e.windup=e.windupDuration=e.boss?1.25:.8;const geom=new THREE.CircleGeometry(e.attackRadius,40),mat=new THREE.MeshBasicMaterial({color:'#d66574',transparent:true,opacity:.25,depthWrite:false,side:THREE.DoubleSide});const m=new THREE.Mesh(geom,mat);m.rotation.x=-Math.PI/2;m.position.set(e.attackX,this.world.groundAt(e.attackX,e.attackZ)+.06,e.attackZ);this.scene.add(m);e.telegraph=m;e.play('Punch',true);}
    }
  }
  ring(position,radius,color,life){const m=new THREE.Mesh(new THREE.RingGeometry(.9,1,48),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.7,side:THREE.DoubleSide,depthWrite:false}));m.rotation.x=-Math.PI/2;m.position.set(position.x,Math.max(this.world.groundAt(position.x,position.z),position.y-.7)+.14,position.z);this.scene.add(m);this.effects.push({mesh:m,life,maxLife:life,radius,type:'ring'});}
  spark(position,color,count=8){for(let i=0;i<count;i++){const m=new THREE.Mesh(new THREE.OctahedronGeometry(.07+Math.random()*.1),new THREE.MeshBasicMaterial({color,transparent:true}));m.position.copy(position);this.scene.add(m);this.effects.push({mesh:m,life:.35+Math.random()*.4,maxLife:.8,type:'spark',velocity:new THREE.Vector3((Math.random()-.5)*7,2+Math.random()*4,(Math.random()-.5)*7)});}}
  disposeEffect(m){if(!m)return;m.removeFromParent();m.geometry?.dispose();m.material?.dispose();}
  updateEffects(dt){for(let i=this.projectiles.length-1;i>=0;i--){const b=this.projectiles[i];b.life-=dt;if(b.target&&!b.target.dead){const p=new THREE.Vector3(b.target.x,b.target.root.position.y+(b.target.boss?3.5:1.3),b.target.z),diff=p.sub(b.mesh.position);if(diff.length()<40*dt+.9){this.hit(b.target,b.power,b.element,b.color);b.life=0;}else b.mesh.position.addScaledVector(diff.normalize(),dt*40);}else b.mesh.position.addScaledVector(b.direction,dt*40);if(b.life<=0){this.disposeEffect(b.mesh);this.projectiles.splice(i,1);}}
    for(let i=this.effects.length-1;i>=0;i--){const e=this.effects[i];e.life-=dt;e.mesh.material.opacity=Math.max(0,e.life/e.maxLife);if(e.type==='ring')e.mesh.scale.setScalar(e.radius*(1-e.life/e.maxLife)+.2);else{e.mesh.position.addScaledVector(e.velocity,dt);e.velocity.y-=dt*8;}if(e.life<=0){this.disposeEffect(e.mesh);this.effects.splice(i,1);}}
  }
  cameraStep(dt){if(!this.started){this.camera.position.set(69+Math.sin(this.time*.045)*8,39,82);this.camera.lookAt(0,5,-17);return;}const p=this.player,target=new THREE.Vector3(p.x,p.y+1.6,p.z),distance=this.cameraDistance,offset=new THREE.Vector3(Math.sin(this.cameraYaw)*distance*Math.cos(this.cameraPitch),Math.sin(this.cameraPitch)*distance,Math.cos(this.cameraYaw)*distance*Math.cos(this.cameraPitch)),desired=target.clone().add(offset);desired.y=Math.max(desired.y,this.world.groundAt(desired.x,desired.z)+1.4);
    // Keep the orbit outside campus architecture as well as above terrain.
    for(let t=.85;t>.25;t-=.15){const test=target.clone().lerp(desired,t);if(this.world.blocked(test.x,test.z)&&test.y<14)desired.copy(target).lerp(desired,Math.max(.23,t-.15));}
    this.camera.position.lerp(desired,1-Math.exp(-dt*10));this.camera.lookAt(target);this.sun.position.set(p.x-45,p.y+70,p.z+25);this.sun.target.position.set(p.x,p.y,p.z);this.sun.target.updateMatrixWorld();}
  tick(dt){this.time+=dt;if(!this.paused){this.state.playtime+=dt;this.invul=Math.max(0,this.invul-dt);this.normalCD=Math.max(0,this.normalCD-dt);this.dodgeCD=Math.max(0,this.dodgeCD-dt);this.dodgeTime=Math.max(0,this.dodgeTime-dt);this.attackAnim=Math.max(0,this.attackAnim-dt);this.shieldTime-=dt;if(this.shieldTime<=0)this.shield=0;for(const id of Object.keys(this.skillCD))this.skillCD[id]=Math.max(0,this.skillCD[id]-dt);if(this.keys.j)this.attack('normal');this.movement(dt);this.updateEnemies(dt);this.updateEffects(dt);this.world.update(dt,this.time);this.saveTime+=dt;if(this.saveTime>8){this.save();this.saveTime=0;}}
    this.cameraStep(dt);this.uiTime+=dt;if(this.uiTime>.15){if(this.started)this.ui.update();this.uiTime=0;}}
  frame(){const dt=Math.min(this.clock.getDelta(),.05);this.tick(dt);this.renderer.render(this.scene,this.camera);this.raf=requestAnimationFrame(()=>this.frame());}
  save(show=false){if(!this.ready)return;this.state.position={x:this.player.x,z:this.player.z};const ok=persist(this.state),status=document.querySelector('#save-status');status.textContent=ok?'✓ บันทึกแล้ว':'บันทึกไม่ได้ · สำรองเซฟในเมนู';if(show)this.ui.toast(ok?'บันทึกความคืบหน้าแล้ว':'บันทึกในเบราว์เซอร์ไม่ได้ กรุณาสำรองเซฟ');return ok;}
  replaceState(state){this.state=state;this.applyQuality();this.place(state.position.x,state.position.z);if(this.world.blocked(this.player.x,this.player.z))this.place(0,27);for(const e of this.world.enemies){e.hp=e.maxHP;e.cooldown=3;e.windup=0;if(e.telegraph){this.disposeEffect(e.telegraph);e.telegraph=null;}e.x=e.homeX;e.z=e.homeZ;e.root.position.set(e.x,Math.max(height(e.x,e.z),.35),e.z);}for(const e of this.effects)this.disposeEffect(e.mesh);for(const b of this.projectiles)this.disposeEffect(b.mesh);this.effects=[];this.projectiles=[];this.skillCD={};this.stamina=100;this.shield=0;this.waypoint=null;this.world.restore(state);this.syncHero();persist(state);this.ui.update();}
  sound(kind){if(!this.state.settings.sound)return;try{const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)return;if(!this.audio)this.audio=new Audio();if(this.audio.state==='suspended')this.audio.resume();const seq=kind==='wish'?[523,659,784,1046]:kind==='chest'?[659,880,1046]:kind==='hurt'?[130,85]:kind==='skill'?[330,660]:kind==='burst'?[220,440,880]:kind==='miss'?[190]:[kind==='normal'?420:520];seq.forEach((f,i)=>{const o=this.audio.createOscillator(),a=this.audio.createGain(),t=this.audio.currentTime+i*.08;o.type=kind==='hurt'?'triangle':'sine';o.frequency.setValueAtTime(f,t);a.gain.setValueAtTime(0,t);a.gain.linearRampToValueAtTime(.035,t+.01);a.gain.exponentialRampToValueAtTime(.0001,t+.18);o.connect(a).connect(this.audio.destination);o.start(t);o.stop(t+.2);});}catch{}}
}
export async function boot(){const game=new Game();await game.init();}
