import { HEROES, REGIONS, PUZZLES, getHero, maxHP, attackPower, levelCost } from './data.js';
import { summon, upgrade, validateSave, newState } from './state.js';
import { terrainColor, regionAt } from './terrain.js';
const $=s=>document.querySelector(s);
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export class UI {
  constructor(game){this.game=game;this.panel=$('#panel');this.content=$('#panel-content');this.tab='';this.selectedRegion='campus';this.toastTimer=0;this.bannerTimer=0;this.lastFocus=null;this.mapBackground=this.buildMapBackground();
    $('#close-panel').onclick=()=>this.close();this.panel.addEventListener('cancel',e=>{e.preventDefault();this.close();});
    document.querySelectorAll('[data-menu]').forEach(b=>b.onclick=()=>this.open(b.dataset.menu));
    $('#panel-tabs').addEventListener('click',e=>{const b=e.target.closest('[data-tab]');if(b)this.open(b.dataset.tab);});
    this.content.addEventListener('click',e=>this.action(e));this.content.addEventListener('change',e=>this.setting(e));
    $('#minimap-button').onclick=()=>this.open('map');$('#quest-tracker').onclick=()=>this.open('quests');$('#start-info').onclick=()=>this.open('help');
    $('#party').addEventListener('click',e=>{const b=e.target.closest('[data-switch]');if(b)game.switchHero(Number(b.dataset.switch));});
    $('#interact-button').onclick=()=>game.interact();$('#attack-button').onclick=()=>game.attack('normal');$('#skill-button').onclick=()=>game.attack('skill');$('#burst-button').onclick=()=>game.attack('burst');$('#jump-button').onclick=()=>game.jump();$('#dodge-button').onclick=()=>game.dodge();
  }
  get s(){return this.game.state;}
  progress(value,name){$('#load-bar').style.width=Math.round(value*100)+'%';$('#load-label').textContent=`กำลังโหลดโมเดล 3D · ${Math.round(value*100)}%`;}
  ready(hasSave){$('#load-label').textContent='พร้อมออกเดินทาง · โมเดล 3D โหลดครบ';$('#start-button').disabled=false;$('#start-info').disabled=false;$('#start-button').textContent=hasSave?'เดินทางต่อ':'ออกเดินทาง';$('#start-button').onclick=()=>this.game.start();}
  toast(text,duration=3300){clearTimeout(this.toastTimer);$('#toast').hidden=false;$('#toast').textContent=text;this.toastTimer=setTimeout(()=>$('#toast').hidden=true,duration);}
  banner(region){clearTimeout(this.bannerTimer);const b=$('#region-banner');b.hidden=false;b.querySelector('strong').textContent=region.name;b.querySelector('small').textContent=region.sub;this.bannerTimer=setTimeout(()=>b.hidden=true,3200);}
  tabs(tab){$('#panel-tabs').innerHTML=[['map','แผนที่'],['team','ทีม'],['wish','อัญเชิญ'],['quests','ภารกิจ'],['settings','ตั้งค่า'],['help','วิธีเล่น'],['lore','บันทึกโลก']].map(([id,name])=>`<button data-tab="${id}" class="${id===tab?'active':''}">${name}</button>`).join('');}
  open(tab){if(!this.panel.open){this.lastFocus=document.activeElement;this.panel.showModal();this.game.clearInput();this.game.save();}this.tab=tab;this.tabs(tab);this.content.scrollTop=0;this.render();}
  close(){this.panel.close();this.tab='';this.game.clearInput();this.game.save();if(this.lastFocus?.isConnected)this.lastFocus.focus({preventScroll:true});else $('#view').focus({preventScroll:true});}
  render(){const s=this.s;
    if(this.tab==='team')this.team();else if(this.tab==='wish')this.wish();else if(this.tab==='map')this.map();else if(this.tab==='settings')this.settings();else if(this.tab==='quests')this.quests();else if(this.tab==='lore')this.lore();else this.help();
  }
  update(){const s=this.s,h=getHero(s.party[s.active]),r=s.roster[h.id],hp=maxHP(h,r.level),g=this.game;
    $('#crystal-count').textContent=Math.floor(s.crystals);$('#hero-name').textContent=h.name;$('#hero-level').textContent='Lv. '+r.level;$('#hero-symbol').textContent=h.symbol;$('#hero-symbol').style.color=h.color;$('#skill-icon').textContent=h.symbol;
    $('#hp-fill').style.width=Math.max(0,r.hp/hp*100)+'%';$('#hp-text').textContent=Math.ceil(r.hp)+' / '+hp;$('#stamina-fill').style.width=g.stamina+'%';
    $('#hero-mode').textContent=g.swimming?'ว่ายน้ำ':g.gliding?'ร่อน':g.climbing?'ปีน':g.shield>0?'มีเกราะ':'';
    const compact=innerWidth<700||innerHeight<540,cd=g.skillCD[h.id]||0;$('#skill-cd').textContent=cd>0?cd.toFixed(1)+'s':compact?'สกิล':'E · สกิล';$('#skill-button').classList.toggle('cooldown',cd>0);$('#burst-energy').textContent=compact?(r.energy>=60?'พร้อม':Math.floor(r.energy)+'/60'):(r.energy>=60?'Q · พร้อม':'Q · '+Math.floor(r.energy)+'/60');$('#jump-button small').textContent=compact?(g.gliding?'พับปีก':'กระโดด'):'Space';$('#dodge-button small').textContent=compact?'หลบ':'X · หลบ';$('#attack-button small').textContent=compact?'โจมตี':'J · โจมตี';$('#burst-button').classList.toggle('ready',r.energy>=60);$('#burst-button').disabled=r.energy<60;
    const region=regionAt(g.player.x,g.player.z);$('#region-name').textContent=region.name;$('#region-sub').textContent=region.sub;
    const partyKey=s.active+':'+s.party.map(id=>id+':'+s.roster[id].level+':'+Math.round(s.roster[id].hp)).join(',');if(partyKey!==this.partyKey){this.partyKey=partyKey;$('#party').innerHTML=s.party.map((id,i)=>{const hero=getHero(id),rs=s.roster[id];return `<button data-switch="${i}" class="${i===s.active?'active':''}" style="--hero-color:${hero.color}" aria-label="สลับเป็น ${hero.name} ${i+1}"><span class="sigil">${hero.symbol}</span><span><strong>${hero.name}</strong><small>Lv. ${rs.level}</small><span class="party-bar"><i style="width:${rs.hp/maxHP(hero,rs.level)*100}%"></i></span></span><kbd>${i+1}</kbd></button>`;}).join('');}
    const objectives=this.objective();$('#quest-title').textContent=objectives.title;$('#quest-detail').textContent=objectives.detail;
    const near=g.nearest;$('#interaction').hidden=!near;$('#interact-label').textContent=near?(near.type==='npc'?'คุยกับพี่พิม':near.type==='chest'?'เปิดหีบสำรวจ':s.beacons.includes(near.id)?'พักที่ '+near.name:'เปิด '+near.name):'';
    const boss=g.world.boss,visible=g.started&&!boss.dead&&s.story>=2&&Math.hypot(boss.x-g.player.x,boss.z-g.player.z)<55;$('#boss-hud').hidden=!visible;$('#boss-fill').style.width=boss.hp/boss.maxHP*100+'%';$('#boss-phase').textContent=boss.hp<boss.maxHP*.5?'ระยะที่ 2 · โอเวอร์โหลด':'ระยะที่ 1 · หลบวงโจมตีสีแดง';
    this.drawMinimap();
  }
  objective(){const s=this.s,n=['forest','wetland','wind'].filter(x=>s.beacons.includes(x)).length;return s.story===0?{title:'เสียงเรียกจากลานเกียร์',detail:'คุยกับพี่พิม ◇ ที่หน้าลานเกียร์'}:s.story===1?{title:'ฟื้นฟูโครงข่าย',detail:`เปิดสถานีป่า อุทยาน และเนินกังหัน ${n}/3`}:s.story===2?{title:'ใจกลางเครื่องจักร',detail:'ไปสันเขาศิลา แล้วหยุด ATLAS'}:s.story===3?{title:'แสงที่กลับคืนมา',detail:'กลับไปคุยกับพี่พิมที่ลานเกียร์'}:{title:'โลกกลับมาหมุนอีกครั้ง',detail:`สำรวจหีบ ${s.chests.length}/20 · ท้าบอสซ้ำที่สันเขา`};}
  team(){const s=this.s;this.content.innerHTML=`<div class="panel-top"><div><h2>ทีมสำรวจ</h2><div class="muted">สลับตัวละครเพื่อประสานพลังจากต่างภาควิชา</div></div><span class="pill">แร่ปรับแต่ง ${Math.floor(s.ore)}</span></div><div class="team-note">ทีมปัจจุบัน: ${s.party.map(id=>getHero(id).name).join(' · ')} <br>คลิกสมาชิกในทีมเพื่อควบคุม หรือเลือกคนใหม่แทนช่องที่กำลังใช้อยู่เมื่อทีมครบ 4 คน</div><div class="hero-grid">${HEROES.map(h=>{const r=s.roster[h.id],owned=!!r,inParty=s.party.includes(h.id);return `<article class="card hero-card ${owned?'':'locked'}" style="--hero-color:${h.color}"><div class="hero-card-header"><div class="big-symbol">${h.symbol}</div><div><strong>${h.name}</strong><div class="stars">${'★'.repeat(h.rarity)}</div><div class="dept">${h.dept}</div></div></div><div class="hero-desc">${h.desc}</div><div class="stats">${owned?`<span>Lv. ${r.level} · Resonance ${r.rank}</span><span>ATK ${attackPower(h,r.level,r.rank)}</span>`:'<span>ยังไม่ได้รับ · พบได้จากอัญเชิญ</span>'}</div><div class="hero-card-actions"><button class="${inParty?'secondary':'primary'}" data-action="equip" data-id="${h.id}" ${owned?'':'disabled'}>${inParty?'ควบคุม':'เข้าทีม'}</button><button class="secondary" data-action="upgrade" data-id="${h.id}" ${owned&&r.level<20&&s.ore>=levelCost(r.level)?'':'disabled'}>${owned&&r.level>=20?'ระดับสูงสุด':owned?`เพิ่มระดับ · ${levelCost(r.level)} แร่`:'ยังไม่ปลดล็อก'}</button></div></article>`;}).join('')}</div>`;}
  wish(){const s=this.s;this.content.innerHTML=`<div class="panel-top"><div><h2>อัญเชิญแห่งอินทาเนีย</h2><div class="muted">ใช้คริสตัลที่หาได้จากการเล่น · ไม่มีการซื้อด้วยเงินจริง</div></div><span class="pill">✧ ${Math.floor(s.crystals)}</span></div><div class="wish-layout"><div class="wish-art"><div><div class="eyebrow">STANDARD EXPEDITION</div><h3>พลังจากทุกภาควิชา</h3><p>เมฆ · วิศวกรรมเครื่องกล<br>ริสา · วิศวกรรมนิวเคลียร์<br>และผู้ร่วมสำรวจระดับ 4 ดาว</p></div><div class="wish-sigil">⚙</div><div class="wish-buttons"><button class="secondary" data-action="pull" data-count="1" ${s.crystals>=160?'':'disabled'}>อัญเชิญ 1 · 160 ✧</button><button class="primary" data-action="pull" data-count="10" ${s.crystals>=1600?'':'disabled'}>อัญเชิญ 10 · 1600 ✧</button></div></div><div><h3>โอกาสพื้นฐานต่อครั้ง</h3><table class="rates"><thead><tr><th>รางวัล</th><th>โอกาส</th></tr></thead><tbody><tr><td>ตัวละคร 5 ดาว</td><td>2%</td></tr><tr><td>ตัวละคร 4 ดาว</td><td>12%</td></tr><tr><td>แร่ปรับแต่ง 3 ดาว</td><td>86%</td></tr></tbody></table><div class="muted">การันตีอย่างน้อย 4 ดาวภายใน 10 ครั้ง และ 5 ดาวภายใน 50 ครั้ง แต่ละระดับมีตัวละครที่โอกาสเท่ากัน การได้ 5 ดาวรีเซ็ตทั้งสองตัวนับ</div><div class="pity-box"><div class="card"><strong>${50-s.pity5}</strong><span>ครั้งก่อนการันตี 5 ดาว</span></div><div class="card"><strong>${10-s.pity4}</strong><span>ครั้งก่อนการันตี ≥4 ดาว</span></div></div></div></div><div class="muted" style="margin-top:18px">ตัวละครซ้ำเพิ่ม Resonance สูงสุด 6 (+2 ATK ต่อระดับ) และแร่ 12 ชิ้น ตัวสุ่ม 10 ครั้งใช้กติกาเดียวกับสุ่มทีละครั้ง</div><details class="history"><summary>ประวัติการอัญเชิญ · ${s.totalPulls} ครั้ง</summary>${s.history.length?s.history.slice(0,30).map(r=>`<div class="history-row"><span>${escape(r.name)}</span><span>${'★'.repeat(r.rarity)}</span></div>`).join(''):'<p class="muted">ยังไม่มีประวัติ</p>'}</details>`;}
  showResults(results){this.content.innerHTML=`<div class="panel-top"><div><h2>ผู้ร่วมทางคนใหม่</h2><div class="muted">บันทึกผลแล้ว · คริสตัลคงเหลือ ${this.s.crystals}</div></div></div><div class="result-grid">${results.map((r,i)=>{const h=getHero(r.id);return `<div class="result-card r${r.rarity}" style="animation-delay:${i*.06}s"><span class="symbol">${r.id==='ore'?'◇':h.symbol}</span><div class="stars">${'★'.repeat(r.rarity)}</div><strong>${escape(r.name)}</strong><small>${r.id==='ore'?'เพิ่มแร่ปรับแต่ง':r.duplicate?'Resonance เพิ่ม · แร่ +12':'ตัวละครใหม่ · พร้อมเข้าทีม'}</small></div>`;}).join('')}</div><div class="settings-actions"><button class="secondary" data-action="backwish">อัญเชิญต่อ</button><button class="primary" data-action="openteam">จัดทีม</button></div>`;}
  buildMapBackground(){const c=document.createElement('canvas');c.width=c.height=520;const ctx=c.getContext('2d'),img=ctx.createImageData(520,520);for(let z=0;z<520;z++)for(let x=0;x<520;x++){const a=terrainColor(x-260,z-260),i=(z*520+x)*4;img.data[i]=a[0]*230;img.data[i+1]=a[1]*225;img.data[i+2]=a[2]*218;img.data[i+3]=255;}ctx.putImageData(img,0,0);return c;}
  paintMap(ctx,w,h,mini=false){ctx.clearRect(0,0,w,h);ctx.drawImage(this.mapBackground,0,0,w,h);const sx=w/520,sz=h/520,s=this.s;const point=(x,z)=>[(x+260)*sx,(z+260)*sz];
    ctx.strokeStyle='#e4d8ae80';ctx.lineWidth=mini?1:2;for(const r of REGIONS.slice(1)){ctx.beginPath();ctx.moveTo(...point(0,20));ctx.lineTo(...point(r.x,r.z));ctx.stroke();}
    for(const r of REGIONS){const [x,z]=point(r.x,r.z),on=s.beacons.includes(r.id);ctx.beginPath();ctx.arc(x,z,mini?4:9,0,Math.PI*2);ctx.fillStyle=on?'#f2e5b3':'#29434a';ctx.fill();ctx.lineWidth=1.5;ctx.strokeStyle=r.color;ctx.stroke();if(!mini){ctx.font='14px "Noto Sans Thai", sans-serif';ctx.textAlign='center';ctx.fillStyle='#fff6dc';ctx.shadowColor='#24483c';ctx.shadowBlur=3;ctx.fillText(r.name,x,z-17);ctx.shadowBlur=0;}}
    if(!mini)for(const c of this.game.world.chests){if(s.chests.includes(c.id))continue;const [x,z]=point(c.x,c.z);ctx.fillStyle='#f8d997';ctx.fillRect(x-2,z-2,4,4);}
    if(s.story>=2&&!s.bossDefeated){const b=this.game.world.boss,[x,z]=point(b.x+12,b.z);ctx.fillStyle='#dd8293';ctx.font=mini?'12px sans-serif':'20px sans-serif';ctx.textAlign='center';ctx.fillText('◆',x,z+5);}
    const [x,z]=point(this.game.player.x,this.game.player.z);ctx.save();ctx.translate(x,z);ctx.rotate(-this.game.cameraYaw);ctx.beginPath();ctx.moveTo(0,-(mini?6:10));ctx.lineTo(mini?4:6,mini?4:6);ctx.lineTo(0,mini?2:3);ctx.lineTo(mini?-4:-6,mini?4:6);ctx.closePath();ctx.fillStyle='#ffffff';ctx.fill();ctx.strokeStyle='#31545f';ctx.lineWidth=1;ctx.stroke();ctx.restore();
    const p=this.game.waypoint;if(p){const [px,pz]=point(p.x,p.z);ctx.strokeStyle='#ffdba7';ctx.lineWidth=2;ctx.beginPath();ctx.arc(px,pz,mini?5:13,0,Math.PI*2);ctx.stroke();}
  }
  drawMinimap(){const c=$('#minimap');this.paintMap(c.getContext('2d'),c.width,c.height,true);}
  map(){const s=this.s,r=REGIONS.find(r=>r.id===this.selectedRegion)||REGIONS[0];this.content.innerHTML=`<div class="panel-top"><div><h2>แผนที่อินทาเนีย</h2><div class="muted">เลือกสถานีเพื่อตั้งเป้าหมาย หรือวาร์ปไปสถานีที่เปิดแล้ว</div></div><span class="pill">สถานี ${s.beacons.length}/5</span></div><div class="map-layout"><div class="map-canvas-wrap"><canvas id="world-map" width="650" height="650" aria-label="แผนที่ 5 ภูมิประเทศ"></canvas><div class="map-legend"><span>● สถานี</span><span>◇ หีบ</span><span>◆ บอส</span><span>▲ คุณ</span></div></div><div><div class="region-list">${REGIONS.map(p=>`<button data-action="selectregion" data-id="${p.id}" class="${p.id===r.id?'selected':''}"><strong>${p.icon} ${p.name}</strong><span>${s.beacons.includes(p.id)?'เปิดแล้ว · วาร์ปได้':'ยังไม่เปิด · เดินทางไปสำรวจ'}</span></button>`).join('')}</div><h3>${r.name}</h3><div class="region-info">${r.sub}<br>${r.fact}</div><button class="primary full-width" data-action="waypoint" data-id="${r.id}">ตั้งเป้าหมาย</button><button class="secondary full-width" style="margin-top:8px" data-action="teleport" data-id="${r.id}" ${s.beacons.includes(r.id)?'':'disabled'}>วาร์ปไปสถานี</button></div></div>`;const c=$('#world-map');this.paintMap(c.getContext('2d'),650,650);c.onclick=e=>{const b=c.getBoundingClientRect(),x=(e.clientX-b.left)/b.width*520-260,z=(e.clientY-b.top)/b.height*520-260;let near=null,dist=30;for(const r of REGIONS){const d=Math.hypot(r.x-x,r.z-z);if(d<dist){dist=d;near=r;}}if(near){this.selectedRegion=near.id;this.map();}else{this.game.waypoint={x,z,name:'หมุดสำรวจ'};this.paintMap(c.getContext('2d'),650,650);this.toast('ตั้งหมุดสำรวจแล้ว');}};}
  quests(){const s=this.s;this.content.innerHTML=`<div class="panel-top"><div><h2>บันทึกการเดินทาง</h2><div class="muted">ภารกิจหลัก · แสงเหนือโครงข่าย</div></div><span class="pill">หีบ ${s.chests.length}/20</span></div><div class="quest-list">${[['เสียงเรียกจากลานเกียร์','คุยกับพี่พิมและรับภารกิจฟื้นฟูโครงข่าย · รางวัล 320 ✧'],['ฟื้นฟูโครงข่าย','เปิดสถานีป่าจามจุรี อุทยานร้อยปี และเนินกังหัน โดยแก้ปัญหาที่เครื่องควบคุม · สถานีละ 160 ✧'],['ใจกลางเครื่องจักร','ขึ้นไปสันเขาศิลา สลับเคมีกับไฟฟ้าเพื่อประสานพลัง แล้วหยุด ATLAS · รางวัล 800 ✧'],['แสงที่กลับคืนมา','กลับไปลานเกียร์ คุยกับพี่พิมเพื่อจบเรื่องราว · รางวัล 640 ✧']].map(([title,desc],i)=>`<article class="card ${s.story>i?'done':''}"><span class="quest-number">${s.story>i?'✓':String(i+1).padStart(2,'0')}</span><div><h3>${title}</h3><p>${desc}</p><div class="muted">${s.story>i?'สำเร็จแล้ว':s.story===i?'กำลังทำ':'ยังไม่เริ่ม'}</div></div></article>`).join('')}</div><div class="card"><h3>ออกไปสำรวจ</h3><div class="muted">หีบสำรวจ 20 หีบ · หุ่นลาดตระเวน 16 ตัว · สถานี 5 แห่ง<br>หยุดบอสครั้งแรกแล้วสามารถท้าซ้ำที่สถานีสันเขาเพื่อรับคริสตัลและแร่เพิ่ม</div></div>`;}
  settings(){const s=this.s;this.content.innerHTML=`<div class="panel-top"><div><h2>ตั้งค่าและบันทึก</h2><div class="muted">เกมพักอัตโนมัติขณะเปิดเมนู</div></div><span class="pill">เล่น ${Math.floor(s.playtime/60)} นาที</span></div><div class="settings-grid"><section class="card"><h3>ภาพและการควบคุม</h3><label class="setting-row">คุณภาพภาพ<select data-setting="quality"><option value="auto" ${s.settings.quality==='auto'?'selected':''}>อัตโนมัติ</option><option value="low" ${s.settings.quality==='low'?'selected':''}>ประหยัดพลังงาน</option><option value="high" ${s.settings.quality==='high'?'selected':''}>สูง</option></select></label><label class="setting-row">เสียง<input type="checkbox" data-setting="sound" ${s.settings.sound?'checked':''}></label><label class="setting-row">กลับทิศกล้องแนวตั้ง<input type="checkbox" data-setting="invert" ${s.settings.invert?'checked':''}></label><label class="setting-row">ความไวกล้อง<input type="range" min="0.4" max="2" step="0.1" value="${s.settings.sensitivity}" data-setting="sensitivity"></label><div class="settings-actions"><button class="secondary" data-action="fullscreen">เต็มหน้าจอ</button><button class="secondary" data-action="touch">${document.body.classList.contains('touch')?'ซ่อน':'แสดง'}ปุ่มสัมผัส</button></div></section><section class="card"><h3>เซฟของคุณ</h3><div class="muted">บันทึกอัตโนมัติในเบราว์เซอร์นี้ การล้างข้อมูลเว็บจะลบเซฟด้วย ดาวน์โหลดไฟล์สำรองเพื่อย้ายไปอีกเครื่อง</div><div class="settings-actions"><button class="primary" data-action="export">สำรองเซฟ</button><button class="secondary" data-action="import">นำเข้าเซฟ</button></div><input id="import-save" type="file" accept="application/json,.json" hidden><div class="settings-actions"><button class="secondary" data-action="save">บันทึกตอนนี้</button><button class="secondary danger" data-action="reset">เริ่มเกมใหม่</button></div><div id="reset-box"></div></section></div><p class="muted">คุณภาพอัตโนมัติลดความละเอียดและเงาสำหรับมือถือ หากภาพกระตุกให้ใช้โหมดประหยัดพลังงาน</p>`;$('#import-save').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(f.size>200000){this.toast('ไฟล์เซฟใหญ่เกินไป');return;}try{const s=validateSave(JSON.parse(await f.text()));this.game.replaceState(s);this.close();this.toast('นำเข้าเซฟสำเร็จ');}catch(err){this.toast('นำเข้าไม่ได้: '+err.message);}};}
  help(){this.content.innerHTML=`<div class="panel-top"><div><h2>ออกเดินทางอย่างไร</h2><div class="muted">อินทาเนีย · เกมผจญภัย 3D ฉบับย่อ</div></div></div><div class="info-grid"><section class="card"><h3>การควบคุมบนคอม</h3><table class="controls-table"><tbody>${[['เดิน / วิ่ง','W A S D / Shift'],['หมุนกล้อง / ซูม','ลากเมาส์ / ล้อเมาส์'],['กระโดด / เปิด–ปิดเครื่องร่อน','Space / Space กลางอากาศ'],['ปีนเนินชัน','C ค้าง พร้อมเดิน'],['โจมตี / สกิล / อัลติเมต','J / E / Q'],['หลบ / ปฏิสัมพันธ์','X / F'],['สลับตัวละคร','1 – 4'],['แผนที่ / ทีม / อัญเชิญ','M / T / G'],['พักเกม / วิธีเล่น','Esc / H']].map(([a,b])=>`<tr><td>${a}</td><td>${b}</td></tr>`).join('')}</tbody></table></section><section class="card"><h3>การควบคุมบนมือถือ</h3><p>ใช้จอยซ้ายเดิน กดวิ่งค้างเพื่อวิ่ง กดปีนค้างบนเนินชัน ลากบนพื้นที่โลกเพื่อหมุนกล้อง ใช้ปุ่มด้านขวาโจมตี สกิล หลบ และกระโดด กดกระโดดอีกครั้งกลางอากาศเพื่อร่อน</p><h3 style="margin-top:20px">ประสานพลังให้เกิดผล</h3><p>เคมี + ไฟฟ้า: เร่งปฏิกิริยา ×1.8<br>โยธา + เครื่องกล: ส่งผ่านแรง ×2<br>สายอื่นต่างชนิด: ประสานพลัง ×1.4<br>พลังบนศัตรูอยู่ 6 วินาที โจมตีด้วยอีกสายระหว่างนั้น</p><h3 style="margin-top:20px">เริ่มจากลานเกียร์</h3><p>คุยกับพี่พิม เปิดสถานี 3 ภูมิประเทศ แล้วไปสันเขาศิลา หีบและหุ่นให้คริสตัลฟรี พักที่สถานีเพื่อเติมพลังทีม เพิ่มระดับด้วยแร่ในเมนูทีม</p></section></div><p class="muted">รองรับ WebGL 2 · เกมเล่นคนเดียว · ข้อมูลบันทึกในเครื่อง · กดปุ่มปิดเมนูเพื่อเริ่มหรือกลับไปเล่น</p>`;}
  lore(){this.content.innerHTML=`<div class="panel-top"><div><h2>บันทึกโลกและแหล่งอ้างอิง</h2><div class="muted">ข้อมูลจริงเป็นแรงบันดาลใจของโลกสมมติ</div></div></div><div class="info-grid">${REGIONS.map(r=>`<article class="card"><h3>${r.icon} ${r.name}</h3><p>${r.fact}</p><p style="margin-top:10px"><a href="${r.source}" target="_blank" rel="noopener">อ่านแหล่งอ้างอิง</a></p></article>`).join('')}<article class="card"><h3>จุดเริ่มของอินทาเนีย</h3><p>ประวัติคณะระบุการเริ่มโรงเรียนยันตรศึกษาเมื่อ 1 มิถุนายน พ.ศ. 2456 จึงใช้เลข 1913 เป็นเมล็ดสร้างโลก สายพลังตั้งตามภาควิชาที่มีอยู่จริง ตัวละคร เนื้อเรื่อง และแผนที่สร้างขึ้นใหม่</p><p style="margin-top:10px"><a href="https://www.eng.chula.ac.th/th/about/instructor" target="_blank" rel="noopener">ประวัติคณะ</a> · <a href="https://www.eng.chula.ac.th/th/departments" target="_blank" rel="noopener">ภาควิชา</a></p></article></div><div class="prose"><h3 style="margin-top:24px">โมเดลและเทคโนโลยี</h3><p>โมเดลตัวละครและแอนิเมชัน: KayKit Adventurers โดย Kay Lousberg (CC0) · โมเดลธรรมชาติ: Kenney Nature Kit (CC0) · หุ่นยนต์: RobotExpressive โดย Quaternius ผ่านตัวอย่าง Three.js (CC0) · เอนจิน Three.js (MIT) ทุกโมเดลเก็บในเกมโดยตรง</p><p>เกมแฟนเมด ไม่ได้เป็นผลิตภัณฑ์ทางการของจุฬาลงกรณ์มหาวิทยาลัย ไม่มีสินทรัพย์ ตัวละคร เพลง หรือโลโก้จาก Genshin Impact การประสานพลังเป็นกติกาเกม ไม่ใช่แบบจำลองฟิสิกส์หรือเคมี</p><a href="./docs/RESEARCH.md" target="_blank" rel="noopener">บันทึกการค้นคว้า</a> · <a href="./docs/ASSETS.md" target="_blank" rel="noopener">แหล่งที่มาโมเดล</a> · <a href="./docs/QA.md" target="_blank" rel="noopener">รายงานการตรวจระบบ</a></div>`;}
  dialogue(title,text,buttons){this.open('dialogue');this.content.innerHTML=`<section class="dialogue"><div class="eyebrow">บันทึกจากโครงข่าย</div><h2>${title}</h2><p>${text}</p><div class="settings-actions">${buttons.map(b=>`<button class="${b.primary?'primary':'secondary'}" data-action="${b.action}" ${b.id?`data-id="${b.id}"`:''}>${b.label}</button>`).join('')}</div></section>`;}
  puzzle(id,feedback=''){const p=PUZZLES[id];this.open('puzzle');this.content.innerHTML=`<section class="dialogue"><div class="eyebrow">ปรับเทียบสถานี · ${REGIONS.find(r=>r.id===id).name}</div><h2>คืนพลังให้โครงข่าย</h2><p>${p.question}</p><div class="answer-list">${p.answers.map((a,i)=>`<button class="secondary" data-action="answer" data-id="${id}" data-answer="${i}">${a}</button>`).join('')}</div>${feedback?`<div class="feedback">${feedback}</div>`:`<div class="muted">${p.hint}</div>`}</section>`;}
  async action(e){const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action,id=b.dataset.id,s=this.s,g=this.game;
    if(a==='equip'){if(!s.roster[id]||s.roster[id].hp<=0){this.toast('สมาชิกนี้หมดสภาพ พักที่สถานีเพื่อฟื้นฟู');return;}const i=s.party.indexOf(id);if(i>=0)g.switchHero(i);else{if(s.party.length<4){s.party.push(id);s.active=s.party.length-1;}else s.party[s.active]=id;g.syncHero();}g.save();this.team();}
    else if(a==='upgrade'){if(upgrade(s,id)){g.save();this.team();this.toast('เพิ่มระดับ '+getHero(id).name+' แล้ว');}}
    else if(a==='pull'){const out=summon(s,Number(b.dataset.count));if(out.ok){g.save();g.syncHero();g.sound('wish');this.showResults(out.results);}else this.toast('คริสตัลไม่พอ ออกสำรวจเพื่อรับเพิ่ม');}
    else if(a==='backwish')this.wish();else if(a==='openteam')this.open('team');
    else if(a==='selectregion'){this.selectedRegion=id;this.map();}
    else if(a==='waypoint'){const r=REGIONS.find(r=>r.id===id);g.waypoint={x:r.x,z:r.z,name:r.name};this.close();this.toast('ตั้งเป้าหมาย '+r.name);}
    else if(a==='teleport'){if(s.beacons.includes(id)){g.teleport(id);this.close();}}
    else if(a==='export'){g.save();const blob=new Blob([JSON.stringify(s,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='inthania-save.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),5000);this.toast('ดาวน์โหลดไฟล์สำรองเซฟแล้ว');}
    else if(a==='import')$('#import-save').click();else if(a==='save')g.save(true);
    else if(a==='reset')$('#reset-box').innerHTML='<div class="reset-confirm">เริ่มใหม่จะลบความคืบหน้าและผลสุ่มในเบราว์เซอร์นี้ ควรสำรองเซฟก่อน<div class="settings-actions"><button class="secondary" data-action="cancelreset">ยกเลิก</button><button class="secondary danger" data-action="confirmreset">ยืนยันเริ่มใหม่</button></div></div>';
    else if(a==='cancelreset')$('#reset-box').innerHTML='';else if(a==='confirmreset'){g.replaceState(newState());this.close();this.toast('เริ่มการเดินทางใหม่');}
    else if(a==='fullscreen'){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{this.toast('เบราว์เซอร์นี้ไม่รองรับเต็มหน้าจอ');}}
    else if(a==='touch'){document.body.classList.toggle('touch');this.settings();}
    else if(a==='acceptquest'){if(s.story===0){s.story=1;s.crystals+=320;g.waypoint={...REGIONS[1]};g.save();}this.close();this.toast('รับภารกิจฟื้นฟูโครงข่าย · +320 ✧');}
    else if(a==='finishquest'){if(s.story===3){s.story=4;s.crystals+=640;s.ore+=30;g.save();}this.dialogue('แสงเหนือโครงข่าย','เสียงเครื่องจักรกลับมาดังอีกครั้ง การเดินทางนี้สำเร็จเพราะพลังของแต่ละภาควิชาเชื่อมถึงกัน โลกยังมีหีบและมุมที่คุณยังไม่เคยสำรวจ',[{label:'ออกสำรวจต่อ',action:'close',primary:true}]);g.sound('wish');}
    else if(a==='answer'){const p=PUZZLES[id];if(Number(b.dataset.answer)===p.correct){g.activateBeacon(id);this.dialogue('ปรับเทียบสำเร็จ',p.explanation+'<br>สถานีเปิดแล้ว · คริสตัล +160 · แร่ +10',[{label:'เดินทางต่อ',action:'close',primary:true}]);}else{this.puzzle(id,'ยังไม่ตรงกับสมดุลของเครื่อง ลองอีกครั้ง · '+p.hint);g.sound('miss');}}
    else if(a==='heal'){g.heal();g.save();this.close();this.toast('ฟื้นฟูทีมและความอึดแล้ว');}
    else if(a==='repeatboss'){g.repeatBoss();this.close();}
    else if(a==='close')this.close();
  }
  setting(e){const el=e.target,k=el.dataset.setting;if(!k)return;this.s.settings[k]=el.type==='checkbox'?el.checked:el.type==='range'?Number(el.value):el.value;if(k==='quality')this.game.applyQuality();this.game.save();}
  damage(text,position,color,reaction=false){const v=position.clone().project(this.game.camera);if(v.z>1)return;const r=$('#view').getBoundingClientRect(),el=document.createElement('span');el.className='damage-number'+(reaction?' reaction':'');el.textContent=text;el.style.left=(v.x*.5+.5)*r.width+'px';el.style.top=(-v.y*.5+.5)*r.height+'px';if(color)el.style.color=color;$('#damage-numbers').appendChild(el);setTimeout(()=>el.remove(),850);}
}
