// Original educational summaries. Source scope and school differences are explicit.
export const REVIEWED = '10 September 2026';
export const LESSONS = [
  {id:'core',name:'Core types',subtitle:'Start with motivation',description:'Explore nine recurring patterns of attention, motivation, and self-protection. Select a number to begin.'},
  {id:'subtypes',name:'Instincts & subtypes',subtitle:'Discover all 27 variations',description:'See how a core pattern combines with self-preservation, social, or sexual instinct. Compare the three variations within each type.'},
  {id:'wings',name:'Wings',subtitle:'Explore your neighbours',description:'A wing is an adjacent type on the circle. Explore how either neighbour can add a different emphasis to the same core pattern.'},
  {id:'arrows',name:'Arrows',subtitle:'Follow the connections',description:'Each type connects to two others. Explore the traditional growth and stress map, then compare a perspective that draws on both connections.'},
  {id:'triads',name:'Triads',subtitle:'See the shared patterns',description:'A triad groups three types around a shared theme. Switch frameworks to see what each grouping helps you notice.'}
];

export const TYPES = [
  {id:1,name:'The Reformer',center:'body',quote:'I want to get it right.',desire:'To live with integrity and be good.',fear:'Being corrupt, defective, or wrong.',summary:'Attention goes to the gap between reality and an inner standard. Improvement can feel like a responsibility, with an inner critic monitoring mistakes and impulses.',gift:'Discernment, conscientiousness, and a willingness to improve what is unfair or ineffective.',trap:'Standards can harden into criticism. Anger may become tension or resentment when it feels unacceptable to express.',practice:'Try completing one low-stakes task to a clearly defined “good enough” standard.',reflection:'When did “I prefer this” become “this is the only right way”? What would flexibility protect?',scenario:'Two classmates both check a report twice. One worries about its accuracy and whether it meets their own standards; the other worries about letting the group down. The visible action alone cannot settle their type.',growth:7,stress:4,growthText:'More openness to enjoyment, spontaneity, and alternatives.',stressText:'More brooding, comparison, and feeling misunderstood.',bothText:'Seven can invite play; Four can invite honest recognition of feelings and needs.',wings:{9:'Combine a concern for integrity with Nine’s steadiness and perspective-taking. The result may look more restrained or contemplative, while the core concern remains doing what is right.',2:'Combine a concern for integrity with Two’s attention to relationships. Improvement may become more personal and supportive, while the core concern remains doing what is right.'}},
  {id:2,name:'The Helper',center:'heart',quote:'I want to matter to you.',desire:'To feel loved and wanted.',fear:'Being unwanted or unworthy of love.',summary:'Attention goes to relationships and what others need. Giving and being important to someone can become a way to secure affection, while personal needs stay out of view.',gift:'Warmth, generosity, and sensitivity to other people’s needs.',trap:'Unspoken expectations can turn help into a bid for appreciation. Resentment may signal a neglected need or boundary.',practice:'Ask directly for one thing you need, without first earning it by helping.',reflection:'If nobody needed my help today, what would I still want or need?',scenario:'A friend brings everyone coffee. They might enjoy generosity, want connection, follow a routine, or hope to be indispensable. Ask what made the gesture feel important, rather than typing the gesture.',growth:4,stress:8,growthText:'More contact with personal feelings, needs, and identity.',stressText:'More demanding or controlling attempts to get needs met.',bothText:'Four can support self-awareness; Eight can support direct requests and boundaries.',wings:{1:'Blend Two’s relational focus with One’s concern for responsibility. Helping may take a conscientious, service-oriented form; being loved remains the core theme.',3:'Blend Two’s relational focus with Three’s energy for accomplishment. Helping may become more outgoing or visible; being loved remains the core theme.'}},
  {id:3,name:'The Achiever',center:'heart',quote:'I want what I do to count.',desire:'To feel valuable and worthwhile.',fear:'Being without worth apart from achievement.',summary:'Attention goes to goals, effectiveness, and what a setting rewards. Adapting to an image of success can obscure personal feelings and the question of what is truly meaningful.',gift:'Adaptability, motivation, and the ability to turn goals into results.',trap:'Worth can become conditional on performance. A polished image may hide exhaustion or uncertainty about personal priorities.',practice:'Make one choice because it matters to you, even if nobody will notice.',reflection:'What would I still care about if it brought no recognition or status?',scenario:'A student volunteers to present the project. They might want recognition, enjoy the topic, help a nervous teammate, or practise a skill. Explore the motivation before assigning a type.',growth:6,stress:9,growthText:'More cooperation, commitment, and investment in shared goals.',stressText:'More disengagement, passivity, or avoidance of priorities.',bothText:'Six can support shared commitment; Nine can support slowing down and reconnecting.',wings:{2:'Blend Three’s achievement focus with Two’s relational sensitivity. Accomplishment may involve more connecting and encouraging; the core concern is still value.',4:'Blend Three’s achievement focus with Four’s personal expression. Accomplishment may carry a more distinctive or reflective style; the core concern is still value.'}},
  {id:4,name:'The Individualist',center:'heart',quote:'I want to be true to myself.',desire:'To understand and express a meaningful identity.',fear:'Having no identity or personal significance.',summary:'Attention goes to personal meaning, emotional experience, and what seems missing. Comparing an ordinary present with an ideal can intensify a feeling of being different or deficient.',gift:'Emotional honesty, creative expression, and sensitivity to nuance.',trap:'A passing feeling can become a fixed identity. Longing and comparison may eclipse what is present and workable.',practice:'Take one meaningful action today without waiting for a particular mood.',reflection:'What is available right now that I overlook when I focus on what is missing?',scenario:'Someone makes unusual art. That does not establish Type Four. The learning question is whether identity, authenticity, or a perceived lack keeps organising their attention across situations.',growth:1,stress:2,growthText:'More grounded action, consistency, and objective perspective.',stressText:'More clinging or over-involvement in important relationships.',bothText:'One can support steady action; Two can support warmth and attention to others.',wings:{3:'Blend Four’s identity focus with Three’s drive for expression through achievement. There may be more interest in an audience; authenticity remains central.',5:'Blend Four’s identity focus with Five’s inquiry and privacy. There may be more inward exploration; authenticity remains central.'}},
  {id:5,name:'The Investigator',center:'head',quote:'I want to understand before I engage.',desire:'To feel capable and competent.',fear:'Being helpless, incapable, or overwhelmed.',summary:'Attention goes to understanding and conserving time, energy, and resources. Stepping back can create insight, but preparation can also become a substitute for participation.',gift:'Independent thinking, concentration, and careful observation.',trap:'Protecting energy too tightly can increase isolation. Gathering more information may postpone action indefinitely.',practice:'Try one small action before you feel completely prepared.',reflection:'What am I waiting to know before participating? How much information is enough for the next step?',scenario:'A quiet person reads during a break. They might be curious, tired, shy, or simply enjoying the book. A Five hypothesis would require a broader pattern around competence and conserving resources.',growth:8,stress:7,growthText:'More decisiveness, confidence, and active engagement.',stressText:'More scattered activity and restless distraction.',bothText:'Eight can support engagement; Seven can support experimentation and wider possibilities.',wings:{4:'Blend Five’s inquiry with Four’s attention to personal meaning. Exploration may be more imaginative or individual; understanding remains the core strategy.',6:'Blend Five’s inquiry with Six’s scrutiny and testing. Exploration may be more systematic or practically investigative; understanding remains the core strategy.'}},
  {id:6,name:'The Loyalist',center:'head',quote:'I want something I can rely on.',desire:'To have support, security, and guidance.',fear:'Facing uncertainty without support or guidance.',summary:'Attention goes to reliability, possible risks, and who or what can be trusted. Seeking reassurance and challenging authority can both be attempts to establish security.',gift:'Commitment, troubleshooting, courage, and attention to consequences.',trap:'Checking can feed further doubt. Threats may be assumed without enough evidence, or certainty borrowed from an authority.',practice:'Separate what you know from what you predict before choosing a next step.',reflection:'Which concern is supported by evidence, and which is a possibility my mind is rehearsing?',scenario:'A teammate challenges the plan. They might distrust the assumptions, care about quality, or resist being controlled. A Six pattern concerns the search for trustworthy support, not disagreement by itself.',growth:9,stress:3,growthText:'More calm, trust, and ability to tolerate uncertainty.',stressText:'More competitive striving and concern with appearances.',bothText:'Nine can support steadiness; Three can support confident action and follow-through.',wings:{5:'Blend Six’s security focus with Five’s independent analysis. Verification may lean toward research and systems; reliable support remains the core concern.',7:'Blend Six’s security focus with Seven’s possibilities and sociability. Reassurance may involve more engagement and humour; reliable support remains the core concern.'}},
  {id:7,name:'The Enthusiast',center:'head',quote:'I want to keep possibility alive.',desire:'To feel satisfied and fulfilled.',fear:'Being trapped in deprivation or pain.',summary:'Attention goes to options, plans, and what could be enjoyable. Anticipation can offer freedom, but constant movement may keep difficult feelings or limits out of awareness.',gift:'Curiosity, inventiveness, optimism, and enthusiasm for possibilities.',trap:'Chasing the next option can fragment attention. Positive reframing may happen before disappointment has been acknowledged.',practice:'Stay with one worthwhile activity after its novelty fades.',reflection:'What feeling appears when I stop planning the next enjoyable thing?',scenario:'Someone proposes a weekend trip. That could express exploration, connection, or escape. Look for the recurring function of keeping options open, rather than assuming every traveller is Seven.',growth:5,stress:1,growthText:'More sustained focus, depth, and appreciation of the present.',stressText:'More rigid criticism and insistence on a correct approach.',bothText:'Five can support depth; One can support limits, discernment, and completion.',wings:{6:'Blend Seven’s possibilities with Six’s attention to people and security. Exploration may be more companionable or cautious; freedom and fulfilment remain central.',8:'Blend Seven’s possibilities with Eight’s assertive energy. Exploration may be more direct or enterprising; freedom and fulfilment remain central.'}},
  {id:8,name:'The Challenger',center:'body',quote:'I want to stand on my own terms.',desire:'To protect oneself and direct one’s own life.',fear:'Being harmed, controlled, or made powerless.',summary:'Attention goes to power, boundaries, and whether others are trustworthy. Direct action can feel protective, while vulnerability may seem to expose an unacceptable risk.',gift:'Directness, resourcefulness, decisiveness, and protective strength.',trap:'Intensity can crowd out other voices. Rejecting vulnerability may make receiving support difficult.',practice:'Name one vulnerable feeling without turning it immediately into action or control.',reflection:'What am I protecting, and does my intensity help the other person understand it?',scenario:'A group leader makes a firm decision. This alone does not establish Eight. Explore whether autonomy and resisting control consistently drive the action, rather than equating leadership with a type.',growth:2,stress:5,growthText:'More openness, care, and willingness to connect.',stressText:'More retreat, secrecy, and defensive isolation.',bothText:'Two can support care; Five can support reflection and restraint before acting.',wings:{7:'Blend Eight’s autonomy with Seven’s appetite for possibilities. Action may be more expansive or adventurous; self-direction remains the core concern.',9:'Blend Eight’s autonomy with Nine’s steadiness. Action may be more measured or quietly protective; self-direction remains the core concern.'}},
  {id:9,name:'The Peacemaker',center:'body',quote:'I want to stay connected and at ease.',desire:'To have inner stability and peace.',fear:'Loss, separation, or disruption of connection.',summary:'Attention goes to maintaining harmony and accommodating different perspectives. Personal priorities can fade when asserting them seems likely to disturb an important connection.',gift:'Receptivity, steadiness, and the ability to hold several perspectives.',trap:'Avoiding tension can become avoidance of personal priorities. Unexpressed resistance may appear as delay or stubbornness.',practice:'State a clear preference before asking what everyone else wants.',reflection:'Where have I said “it does not matter” when I actually have a preference?',scenario:'Someone agrees with the group’s restaurant choice. They may have no preference at all. A Nine hypothesis needs a repeated pattern of losing personal priorities to preserve ease or connection.',growth:3,stress:6,growthText:'More initiative, energy, and investment in personal priorities.',stressText:'More worry, self-doubt, and suspicious interpretation.',bothText:'Three can support initiative; Six can support questioning and recognising real concerns.',wings:{8:'Blend Nine’s harmony focus with Eight’s boundary-setting. A calmer style may coexist with stubborn resolve; stability remains central.',1:'Blend Nine’s harmony focus with One’s standards. Mediation may be more conscientious or idealistic; stability remains central.'}}
];

// Names and countertypes follow the Chestnut–Paes presentation of Naranjo's tradition.
export const SUBTYPES = {
  1:{sp:{name:'Worry',text:'Improvement turns inward: responsibility and careful preparation can serve a need to prevent mistakes. Irritation is often contained, so a friendly manner may coexist with strong self-criticism.'},so:{name:'Non-adaptability',text:'Correctness becomes something to model for a group. Clear standards can support teaching and reform, but certainty about the right example can make adaptation difficult.'},sx:{name:'Zeal',counter:true,text:'The impulse to improve is directed forcefully outward. This subtype may express anger and reforming energy more openly, unlike the familiar image of the restrained One.'}},
  2:{sp:{name:'Privilege',counter:true,text:'Connection may be sought through charm and a wish to be cared for simply for being oneself. Pride can be less obvious than in the familiar image of the indispensable helper.'},so:{name:'Ambition',text:'Relationships and helpfulness can serve a wish to become influential within a group. Being valued for a significant role may matter more than private closeness.'},sx:{name:'Seduction / aggression',text:'Attention concentrates on attracting a particular person and securing a special bond. Personal appeal can become mixed with pressure for attention. This describes a relational strategy, not a requirement for sexual behaviour.'}},
  3:{sp:{name:'Security',counter:true,text:'Worth is pursued through dependable work, effectiveness, and material stability. Open self-promotion may feel uncomfortable; being admirable for not showing vanity can itself become an image.'},so:{name:'Prestige',text:'Achievement is directed toward visible recognition, status, and influence. Reading what an audience values can help performance, while making external approval especially compelling.'},sx:{name:'Charisma',text:'Achievement centres on being personally attractive and supporting the success of important others. Value may be experienced through being an appealing partner or promoting someone close.'}},
  4:{sp:{name:'Tenacity',counter:true,text:'Pain and perceived deficiency can become private endurance and strenuous effort. This subtype may show less outward emotional drama, trying to earn love through bearing difficulty rather than displaying it.'},so:{name:'Shame',text:'Comparison turns toward belonging and a sense of being less adequate than others. Emotional pain may be readily expressed; attention can stay on what appears missing in the self.'},sx:{name:'Competition',text:'Comparison can become an urge to outdo others or challenge perceived disadvantages. Deficiency may be expressed as anger and rivalry rather than quiet self-doubt.'}},
  5:{sp:{name:'Castle',text:'Safety is sought through protected space, limited demands, and clear boundaries. Keeping needs small can preserve independence, but may also narrow opportunities for connection.'},so:{name:'Totem',text:'Connection develops through shared knowledge, expertise, or a valued ideal. Intellectual belonging can feel safer than emotional exposure, with authorities or specialised interests taking on unusual importance.'},sx:{name:'Confidence',counter:true,text:'Privacy coexists with a search for exceptional trust and intimacy. A rich emotional or romantic inner world may emerge in a chosen bond, while autonomy still matters strongly.'}},
  6:{sp:{name:'Warmth',text:'Security is sought through trusted alliances, friendliness, and mutual protection. Doubt may be visible, with closeness providing reassurance against uncertainty.'},so:{name:'Duty',text:'Security is sought through rules, principles, or a reliable system of authority. Precision and certainty can help manage doubt, even when the underlying concern remains uncertainty.'},sx:{name:'Strength / beauty',counter:true,text:'Fear is met by moving toward threat with strength, readiness, or an intimidating presentation. Apparent fearlessness is understood here as a way of managing fear, not its absence.'}},
  7:{sp:{name:'Keepers of the castle',text:'Possibility-seeking becomes practical: useful alliances, opportunities, and enjoyable resources help secure a satisfying life. Networking can become a way to keep options and advantages available.'},so:{name:'Sacrifice',counter:true,text:'The drive for enjoyment may be redirected into service and idealism. Giving up personal wants can support others, while also feeding a wish to be recognised as good or selfless.'},sx:{name:'Suggestibility',text:'Possibility is amplified through imagination, idealisation, and fascination. An exciting person or idea can promise something beyond ordinary life, making actual limits easier to overlook.'}},
  8:{sp:{name:'Satisfaction',text:'Autonomy is channelled into getting practical needs met promptly. A direct, self-reliant approach to resources can be less outwardly expressive than other Eight styles.'},so:{name:'Solidarity',counter:true,text:'Strength is mobilised for loyalty, protection, or a group’s needs. The protective role can soften the familiar image of overt aggression, while retaining Eight’s forcefulness.'},sx:{name:'Possession',text:'Intensity is directed toward influence, attention, and powerful connection. The wish to feel fully engaged can become controlling when others’ autonomy is overlooked.'}},
  9:{sp:{name:'Appetite',text:'Comfort and familiar routines can become the main way to stay settled. Practical activity or sensory ease may distract from naming personal feelings, priorities, and desires.'},so:{name:'Participation',counter:true,text:'Belonging is maintained through involvement and substantial work for groups. Being busy can conceal the Nine pattern of overlooking personal priorities; low visible energy is not required.'},sx:{name:'Fusion',text:'Connection centres on merging with a significant other’s views or agenda. Warmth and receptivity may make personal preferences harder to distinguish or assert.'}}
};

export const INSTINCTS = {
 sp:{name:'Self-preservation',short:'SP',question:'What keeps me resourced?',text:'Attention to the body, resources, safety, and practical continuity.'},
 so:{name:'Social',short:'SO',question:'Where do I belong and contribute?',text:'Attention to belonging, roles, social signals, and participation.'},
 sx:{name:'Sexual / one-to-one',short:'SX',question:'What attracts and engages me intensely?',text:'Attention to attraction and charged connection; terminology varies by school.'}
};

export const TRIADS = {
 centers:{name:'Centers',question:'Which emotional theme organises the pattern?',note:'Everyone uses thinking, feeling, and bodily awareness. A center does not measure intelligence or emotional capacity.',groups:[
  {id:'body',name:'Body / gut',types:[8,9,1],theme:'Anger · autonomy · boundaries',text:'How a person relates to instinct, agency, and anger. Eight expresses force, Nine tends to lose contact with anger, and One tends to restrain it.'},
  {id:'heart',name:'Heart / feeling',types:[2,3,4],theme:'Shame · identity · worth',text:'How a person relates to image and value. Two seeks relational value, Three emphasises achievement, and Four emphasises personal identity.'},
  {id:'head',name:'Head / thinking',types:[5,6,7],theme:'Fear · guidance · security',text:'How a person relates to uncertainty. Five seeks understanding, Six seeks trustworthy support, and Seven seeks options.'}
 ]},
 hornevian:{name:'Hornevian',question:'How do I move to get my needs met?',note:'Also called social stances. “Compliant” means oriented to an inner duty, not necessarily obedient or agreeable.',groups:[
  {id:'assertive',name:'Assertive',types:[3,7,8],theme:'Move against · pursue',text:'Moves forward to pursue needs and influence circumstances.'},
  {id:'compliant',name:'Compliant / dutiful',types:[1,2,6],theme:'Move toward · earn',text:'Looks to responsibility, obligation, or doing what ought to be done.'},
  {id:'withdrawn',name:'Withdrawn',types:[4,5,9],theme:'Move away · retreat',text:'Moves inward or steps back from immediate demands.'}
 ]},
 harmonic:{name:'Harmonic',question:'How do I cope when things go wrong?',note:'A coping pattern is not a fixed skill level. Anyone can be optimistic, competent, or emotionally responsive.',groups:[
  {id:'positive',name:'Positive outlook',types:[2,7,9],theme:'Reframe · reassure',text:'Emphasises hope or what is still good, sometimes bypassing difficulty.'},
  {id:'competency',name:'Competency',types:[1,3,5],theme:'Solve · organise',text:'Emphasises effectiveness and solutions, sometimes setting feelings aside.'},
  {id:'reactive',name:'Reactive / emotional realness',types:[4,6,8],theme:'Express · respond',text:'Emphasises acknowledging the emotional truth and seriousness of a problem.'}
 ]},
 object:{name:'Object relations',question:'How do I relate to getting needs met?',note:'“Attachment” here is an Enneagram category. It is not secure, anxious, or avoidant attachment style, and does not establish a childhood history.',groups:[
  {id:'attachment',name:'Attachment',types:[3,6,9],theme:'Adapt to what is available',text:'Negotiates between personal priorities and external reference points.'},
  {id:'frustration',name:'Frustration',types:[1,4,7],theme:'Compare reality with an ideal',text:'Notices the gap between what is available and what could satisfy.'},
  {id:'rejection',name:'Rejection',types:[2,5,8],theme:'Offer something essential',text:'Emphasises a particular contribution while minimising other needs.'}
 ]}
};

const words=['one','two','three','four','five','six','seven','eight','nine'];
export const SOURCES = {
 system:{title:'How the Enneagram System Works',publisher:'The Enneagram Institute',url:'https://www.enneagraminstitute.com/how-the-enneagram-system-works/',scope:'Core structure, wing adjacency, centers, instincts, and the traditional Riso–Hudson arrow map.',kind:'Teaching source'},
 narrative:{title:'Instinctual Subtypes',publisher:'The Narrative Enneagram',url:'https://www.narrativeenneagram.org/instinctual-subtypes/',scope:'Instinct definitions and an alternative presentation of subtype language.',kind:'Teaching source'},
 subtypes:{title:'The 27 Subtypes',publisher:'Chestnut–Paes Enneagram Academy',url:'https://cpenneagram.com/subtypes',scope:'Subtype names and countertype classifications in the Naranjo / Chestnut tradition.',kind:'Teaching source'},
 triads:{title:'Triads',publisher:'Enneagrammer',url:'https://www.enneagrammer.com/triads',scope:'Hornevian, harmonic, and object-relations memberships. These are school-based frameworks.',kind:'Teaching source'},
 review:{title:'The Enneagram: A systematic review of the literature and directions for future research',publisher:'Hook et al. · Journal of Clinical Psychology · 2021',url:'https://doi.org/10.1002/jclp.23097',scope:'Independent review of empirical evidence, separate from Enneagram schools’ teaching claims.',kind:'Research review'},
 ...Object.fromEntries(TYPES.map(t=>['ei'+t.id,{title:'Type '+t.id+' · '+t.name,publisher:'The Enneagram Institute',url:'https://www.enneagraminstitute.com/type-'+t.id+'/',scope:'Core motivation, recurring strengths and difficulties, and traditional arrow descriptions.',kind:'Teaching source'}])),
 ...Object.fromEntries(TYPES.map(t=>['cp'+t.id,{title:'Type '+words[t.id-1]+' · subtypes and growth',publisher:'Chestnut–Paes Enneagram Academy',url:'https://cpenneagram.com/enneagram-type-'+words[t.id-1],scope:'The three subtype descriptions, countertype status, and using both connecting points for development.',kind:'Teaching source'}]))
};

// Questions assess the taught frameworks, never the learner's personality.
export const QUESTIONS = [
 {id:'c1',lesson:'core',q:'Two people do exactly the same helpful thing. What is the best next question when exploring a core type?',options:['Who did it faster?','What repeatedly motivates each person?','Which person is more extroverted?','Which person gets more praise?'],answer:1,explain:'Similar actions can serve different motives. Investigate recurring attention and motivation across contexts.',sources:['ei2','ei3']},
 {id:'c2',lesson:'core',q:'Which concern most directly fits the Type Five description taught here?',options:['I need everyone to agree.','I must always be admired.','I need to understand enough to feel capable.','I need to be indispensable through helping.'],answer:2,explain:'Five centres on capability and understanding. Quietness or academic ability alone is not enough to infer Five.',sources:['ei5']},
 {id:'c3',lesson:'core',q:'Someone both seeks reassurance and challenges authority. Which type description explicitly allows both?',options:['Only Type One','Only Type Eight','No type can do both','Type Six'],answer:3,explain:'Six can seek support and test it. Cautious and confrontational responses may both organise around security.',sources:['ei6']},
 {id:'c4',lesson:'core',q:'Which statement is the most careful way to use the Enneagram?',options:['Treat it as a reflective framework with limited empirical support.','Use it to diagnose a mental health condition.','Assume one behaviour proves a type.','Rank types from least to most developed.'],answer:0,explain:'A useful reflection is not proof of a personality taxonomy. Type numbers do not rank a person’s maturity.',sources:['review','system']},
 {id:'s1',lesson:'subtypes',q:'What produces 27 subtypes in the model used here?',options:['Nine types × three possible wings','Nine types × three dominant instincts','Nine types × three levels of intelligence','Three types × nine attachment styles'],answer:1,explain:'Each of nine core patterns combines with SP, SO, or SX as the dominant instinct: 9 × 3 = 27.',sources:['subtypes','narrative']},
 {id:'s2',lesson:'subtypes',q:'Does a dominant social instinct necessarily mean someone is extroverted?',options:['Yes, social means outgoing.','Yes, unless they have a withdrawn wing.','No; it concerns social attention and belonging.','No; social means they always avoid groups.'],answer:2,explain:'The model concerns what captures attention. Sociability by itself does not identify an instinct.',sources:['narrative','system']},
 {id:'s3',lesson:'subtypes',q:'In the Chestnut–Paes classification, which Type Six subtype is the countertype?',options:['Self-preservation Six','Social Six','All Six subtypes equally','Sexual Six'],answer:3,explain:'Sexual Six is described as meeting fear through strength and readiness. Looking unafraid is not the same as having no fear.',sources:['cp6']},
 {id:'s4',lesson:'subtypes',q:'What does “countertype” mean in this course?',options:['A subtype whose expression runs against its type’s usual presentation.','A second core type.','A person with no instinct.','A scientifically superior subtype.'],answer:0,explain:'It is a school-specific subtype distinction. The underlying core pattern remains the same.',sources:['subtypes']},
 {id:'w1',lesson:'wings',q:'Which wings are possible for Type Nine?',options:['Three and Six','One and Two','Eight and One','Any two types with a high test score'],answer:2,explain:'Wings are neighbours on the circle, including the wraparound between Nine and One.',sources:['system']},
 {id:'w2',lesson:'wings',q:'What does 5w6 mean?',options:['Type Six with a Five wing','Type Five with a Six wing','An equal combination of Types Five and Six','Type Five becoming Type Six under stress'],answer:1,explain:'The first number names the core type. The number after w names an adjacent wing.',sources:['system']},
 {id:'w3',lesson:'wings',q:'A Type Four relates strongly to Type Nine. Does that make 4w9 a conventional wing?',options:['Yes, if Nine is their second-highest score.','Yes, if they are both withdrawn.','Yes, if they feel calm.','No; Four’s neighbours are Three and Five.'],answer:3,explain:'Shared traits and triad membership do not create a wing. Wing adjacency is a structural rule.',sources:['system','triads']},
 {id:'w4',lesson:'wings',q:'How should the course describe one wing versus two?',options:['Schools differ, and influence can be uneven.','Everyone must have two equal wings.','Everyone must display exactly one wing at all times.','Wings are proven biological categories.'],answer:0,explain:'The Institute discusses a commonly dominant wing while acknowledging variation and disagreement between traditions.',sources:['system','review']},
 {id:'a1',lesson:'arrows',q:'In the traditional Riso–Hudson map, which direction represents growth for Type One?',options:['1 → 4','1 → 7','1 → 2','1 → 9'],answer:1,explain:'One’s traditional growth connection is Seven; its traditional stress connection is Four.',sources:['ei1']},
 {id:'a2',lesson:'arrows',q:'Which are the two actual inner-line connections of Type Nine?',options:['Eight and One','Two and Seven','Three and Six','Four and Five'],answer:2,explain:'The inner triangle joins Three, Six, and Nine. Eight and One are Nine’s wings, not its arrows.',sources:['system','ei9']},
 {id:'a3',lesson:'arrows',q:'Does the course treat an arrow as a guaranteed change of core type?',options:['Yes, every stressful event changes type.','Yes, after sufficient personal growth.','Yes, but only for head types.','No; it is a theoretical connection between patterns.'],answer:3,explain:'The model describes influences or patterns. It neither changes the core label nor predicts every stressful response.',sources:['system','review']},
 {id:'a4',lesson:'arrows',q:'How does the “Both connections” view differ from the traditional growth / stress diagram?',options:['It explores constructive qualities at both connected points.','It gives every type seven new arrows.','It replaces arrows with wings.','It claims that stress is always healthy.'],answer:0,explain:'Chestnut–Paes uses both connected points in growth work. This course keeps that approach distinct from the traditional directional labels.',sources:['cp1']},
 {id:'t1',lesson:'triads',q:'Which types belong to the heart center?',options:['Eight, Nine, One','Five, Six, Seven','Two, Three, Four','Three, Six, Nine'],answer:2,explain:'The heart center contains Two, Three, and Four; its shared theme concerns worth, image, and shame.',sources:['system']},
 {id:'t2',lesson:'triads',q:'Which types form the competency harmonic group?',options:['Two, Seven, Nine','One, Three, Five','Four, Six, Eight','One, Two, Six'],answer:1,explain:'One, Three, and Five are grouped around solving problems through effectiveness, standards, or expertise.',sources:['triads']},
 {id:'t3',lesson:'triads',q:'Which types make up the withdrawn Hornevian group?',options:['One, Two, Six','Three, Seven, Eight','Two, Five, Eight','Four, Five, Nine'],answer:3,explain:'Four, Five, and Nine are described as moving away or inward to meet needs.',sources:['triads']},
 {id:'t4',lesson:'triads',q:'Is the attachment triad the same thing as anxious attachment in relationship psychology?',options:['No; these are different uses of the word.','Yes, all Threes, Sixes, and Nines have anxious attachment.','Yes, but only in adulthood.','Yes, and it proves a particular childhood experience.'],answer:0,explain:'The Enneagram attachment group is Three, Six, and Nine. Its name does not assign a clinical or relationship attachment style.',sources:['triads']}
];

export const getType = id => TYPES.find(t=>t.id===Number(id)) || TYPES[0];
export const getWings = id => [Number(id)===1?9:Number(id)-1,Number(id)===9?1:Number(id)+1];
export const CONNECTIONS = [[1,4],[4,2],[2,8],[8,5],[5,7],[7,1],[9,6],[6,3],[3,9]];
export function point(id,radius=145){const angle=(Number(id)*40-90)*Math.PI/180;return {x:200+radius*Math.cos(angle),y:200+radius*Math.sin(angle)};}
export function makeQuestions(filter='all',random=Math.random){
  const selected=QUESTIONS.filter(q=>filter==='all'||q.lesson===filter).map(q=>({...q,options:[...q.options]}));
  for(let i=selected.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[selected[i],selected[j]]=[selected[j],selected[i]];}
  return selected.map(q=>{const choices=q.options.map((text,index)=>({text,correct:index===q.answer}));for(let i=choices.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[choices[i],choices[j]]=[choices[j],choices[i]];}return {...q,options:choices.map(c=>c.text),answer:choices.findIndex(c=>c.correct)};});
}
